// Code generated by entcascade, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/khanakia/entx/testent/ent/article"
	"github.com/khanakia/entx/testent/ent/category"
	"github.com/khanakia/entx/testent/ent/channel"
	"github.com/khanakia/entx/testent/ent/comment"
	"github.com/khanakia/entx/testent/ent/doc"
	"github.com/khanakia/entx/testent/ent/folder"
	"github.com/khanakia/entx/testent/ent/member"
	"github.com/khanakia/entx/testent/ent/note"
	"github.com/khanakia/entx/testent/ent/post"
	"github.com/khanakia/entx/testent/ent/posttag"
	"github.com/khanakia/entx/testent/ent/profile"
	"github.com/khanakia/entx/testent/ent/revision"
	"github.com/khanakia/entx/testent/ent/team"
	"github.com/khanakia/entx/testent/ent/user"
	"github.com/khanakia/entx/testent/ent/workspace"
)

// inTransaction reports whether the given client is already backed by a
// transaction driver. When true, cascade delete functions reuse the caller's
// transaction instead of starting a new one — the caller retains ownership
// of commit/rollback.
func inTransaction(c *Client) bool {
	_, ok := c.driver.(*txDriver)
	return ok
}

// CascadeDeleteArticleHooks allows injecting business logic around the cascade delete.
// Both hooks run inside the transaction. Return an error to abort and rollback.
type CascadeDeleteArticleHooks struct {
	// Pre runs before any delete operations.
	Pre func(ctx context.Context, client *Client, id int) error
	// Post runs after all deletes (including the entity itself).
	Post func(ctx context.Context, client *Client, id int) error
}

// CascadeDeleteArticle deletes a Article and all its dependent entities in a transaction.
func CascadeDeleteArticle(ctx context.Context, client *Client, id int) error {
	return CascadeDeleteArticleWithHooks(ctx, client, id, CascadeDeleteArticleHooks{})
}

// CascadeDeleteArticleWithHooks deletes a Article and all its dependent entities in a transaction,
// calling the provided hooks inside the transaction boundary.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteArticleWithHooks(ctx context.Context, client *Client, id int, hooks CascadeDeleteArticleHooks) error {
	// Nested-tx path: reuse caller's transaction, no commit/rollback here.
	if inTransaction(client) {
		if hooks.Pre != nil {
			if err := hooks.Pre(ctx, client, id); err != nil {
				return err
			}
		}
		if err := cascadeDeleteArticleOps(ctx, client, id); err != nil {
			return err
		}
		if hooks.Post != nil {
			if err := hooks.Post(ctx, client, id); err != nil {
				return err
			}
		}
		return nil
	}

	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete article: start tx: %w", err)
	}
	if hooks.Pre != nil {
		if err := hooks.Pre(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete article: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := cascadeDeleteArticleOps(ctx, tx.Client(), id); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete article: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if hooks.Post != nil {
		if err := hooks.Post(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete article: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete article: commit: %w", err)
	}
	return nil
}

func cascadeDeleteArticleOps(ctx context.Context, client *Client, id int) error {
	// Soft-delete revisions (soft-delete via deleted_at).
	if err := client.Revision.Update().Where(revision.ArticleID(id)).SetDeletedAt(time.Now()).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: soft-delete revision: %w", err)
	}
	// Delete Article itself.
	if _, err := client.Article.Delete().Where(article.ID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete article: %w", err)
	}
	return nil
}

// CascadeDeleteArticleBatch deletes multiple Article entities and all their dependents in a single transaction.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteArticleBatch(ctx context.Context, client *Client, ids []int) error {
	if len(ids) == 0 {
		return nil
	}
	// Nested-tx path: reuse caller's transaction.
	if inTransaction(client) {
		return cascadeDeleteArticleBatchOps(ctx, client, ids)
	}
	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete article batch: start tx: %w", err)
	}
	if err := cascadeDeleteArticleBatchOps(ctx, tx.Client(), ids); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete article batch: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete article batch: commit: %w", err)
	}
	return nil
}

func cascadeDeleteArticleBatchOps(ctx context.Context, client *Client, ids []int) error {
	// Soft-delete revisions (soft-delete via deleted_at).
	if err := client.Revision.Update().Where(revision.ArticleIDIn(ids...)).SetDeletedAt(time.Now()).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: soft-delete revision: %w", err)
	}
	// Delete Article entities.
	if _, err := client.Article.Delete().Where(article.IDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete article batch: %w", err)
	}
	return nil
}

// CascadeDeleteCategoryHooks allows injecting business logic around the cascade delete.
// Both hooks run inside the transaction. Return an error to abort and rollback.
type CascadeDeleteCategoryHooks struct {
	// Pre runs before any delete operations.
	Pre func(ctx context.Context, client *Client, id int) error
	// Post runs after all deletes (including the entity itself).
	Post func(ctx context.Context, client *Client, id int) error
}

// CascadeDeleteCategory deletes a Category and all its dependent entities in a transaction.
func CascadeDeleteCategory(ctx context.Context, client *Client, id int) error {
	return CascadeDeleteCategoryWithHooks(ctx, client, id, CascadeDeleteCategoryHooks{})
}

// CascadeDeleteCategoryWithHooks deletes a Category and all its dependent entities in a transaction,
// calling the provided hooks inside the transaction boundary.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteCategoryWithHooks(ctx context.Context, client *Client, id int, hooks CascadeDeleteCategoryHooks) error {
	// Nested-tx path: reuse caller's transaction, no commit/rollback here.
	if inTransaction(client) {
		if hooks.Pre != nil {
			if err := hooks.Pre(ctx, client, id); err != nil {
				return err
			}
		}
		if err := cascadeDeleteCategoryOps(ctx, client, id); err != nil {
			return err
		}
		if hooks.Post != nil {
			if err := hooks.Post(ctx, client, id); err != nil {
				return err
			}
		}
		return nil
	}

	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete category: start tx: %w", err)
	}
	if hooks.Pre != nil {
		if err := hooks.Pre(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete category: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := cascadeDeleteCategoryOps(ctx, tx.Client(), id); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete category: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if hooks.Post != nil {
		if err := hooks.Post(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete category: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete category: commit: %w", err)
	}
	return nil
}

func cascadeDeleteCategoryOps(ctx context.Context, client *Client, id int) error {
	// Unlink posts (unlink).
	if err := client.Post.Update().Where(post.CategoryID(id)).ClearCategoryID().Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: unlink post: %w", err)
	}
	// Delete Category itself.
	if _, err := client.Category.Delete().Where(category.ID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete category: %w", err)
	}
	return nil
}

// CascadeDeleteCategoryBatch deletes multiple Category entities and all their dependents in a single transaction.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteCategoryBatch(ctx context.Context, client *Client, ids []int) error {
	if len(ids) == 0 {
		return nil
	}
	// Nested-tx path: reuse caller's transaction.
	if inTransaction(client) {
		return cascadeDeleteCategoryBatchOps(ctx, client, ids)
	}
	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete category batch: start tx: %w", err)
	}
	if err := cascadeDeleteCategoryBatchOps(ctx, tx.Client(), ids); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete category batch: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete category batch: commit: %w", err)
	}
	return nil
}

func cascadeDeleteCategoryBatchOps(ctx context.Context, client *Client, ids []int) error {
	// Unlink posts (unlink).
	if err := client.Post.Update().Where(post.CategoryIDIn(ids...)).ClearCategoryID().Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: unlink post: %w", err)
	}
	// Delete Category entities.
	if _, err := client.Category.Delete().Where(category.IDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete category batch: %w", err)
	}
	return nil
}

// CascadeDeleteDocHooks allows injecting business logic around the cascade delete.
// Both hooks run inside the transaction. Return an error to abort and rollback.
type CascadeDeleteDocHooks struct {
	// Pre runs before any delete operations.
	Pre func(ctx context.Context, client *Client, id int) error
	// Post runs after all deletes (including the entity itself).
	Post func(ctx context.Context, client *Client, id int) error
}

// CascadeDeleteDoc deletes a Doc and all its dependent entities in a transaction.
func CascadeDeleteDoc(ctx context.Context, client *Client, id int) error {
	return CascadeDeleteDocWithHooks(ctx, client, id, CascadeDeleteDocHooks{})
}

// CascadeDeleteDocWithHooks deletes a Doc and all its dependent entities in a transaction,
// calling the provided hooks inside the transaction boundary.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteDocWithHooks(ctx context.Context, client *Client, id int, hooks CascadeDeleteDocHooks) error {
	// Nested-tx path: reuse caller's transaction, no commit/rollback here.
	if inTransaction(client) {
		if hooks.Pre != nil {
			if err := hooks.Pre(ctx, client, id); err != nil {
				return err
			}
		}
		if err := cascadeDeleteDocOps(ctx, client, id); err != nil {
			return err
		}
		if hooks.Post != nil {
			if err := hooks.Post(ctx, client, id); err != nil {
				return err
			}
		}
		return nil
	}

	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete doc: start tx: %w", err)
	}
	if hooks.Pre != nil {
		if err := hooks.Pre(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete doc: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := cascadeDeleteDocOps(ctx, tx.Client(), id); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete doc: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if hooks.Post != nil {
		if err := hooks.Post(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete doc: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete doc: commit: %w", err)
	}
	return nil
}

func cascadeDeleteDocOps(ctx context.Context, client *Client, id int) error {
	// Soft-delete notes (soft-delete via archived_at).
	if err := client.Note.Update().Where(note.DocID(id)).SetArchivedAt(time.Now()).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: soft-delete note: %w", err)
	}
	// Delete Doc itself.
	if _, err := client.Doc.Delete().Where(doc.ID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete doc: %w", err)
	}
	return nil
}

// CascadeDeleteDocBatch deletes multiple Doc entities and all their dependents in a single transaction.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteDocBatch(ctx context.Context, client *Client, ids []int) error {
	if len(ids) == 0 {
		return nil
	}
	// Nested-tx path: reuse caller's transaction.
	if inTransaction(client) {
		return cascadeDeleteDocBatchOps(ctx, client, ids)
	}
	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete doc batch: start tx: %w", err)
	}
	if err := cascadeDeleteDocBatchOps(ctx, tx.Client(), ids); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete doc batch: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete doc batch: commit: %w", err)
	}
	return nil
}

func cascadeDeleteDocBatchOps(ctx context.Context, client *Client, ids []int) error {
	// Soft-delete notes (soft-delete via archived_at).
	if err := client.Note.Update().Where(note.DocIDIn(ids...)).SetArchivedAt(time.Now()).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: soft-delete note: %w", err)
	}
	// Delete Doc entities.
	if _, err := client.Doc.Delete().Where(doc.IDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete doc batch: %w", err)
	}
	return nil
}

// CascadeDeleteFolderHooks allows injecting business logic around the cascade delete.
// Both hooks run inside the transaction. Return an error to abort and rollback.
type CascadeDeleteFolderHooks struct {
	// Pre runs before any delete operations.
	Pre func(ctx context.Context, client *Client, id int) error
	// Post runs after all deletes (including the entity itself).
	Post func(ctx context.Context, client *Client, id int) error
}

// CascadeDeleteFolder deletes a Folder and all its dependent entities in a transaction.
func CascadeDeleteFolder(ctx context.Context, client *Client, id int) error {
	return CascadeDeleteFolderWithHooks(ctx, client, id, CascadeDeleteFolderHooks{})
}

// CascadeDeleteFolderWithHooks deletes a Folder and all its dependent entities in a transaction,
// calling the provided hooks inside the transaction boundary.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteFolderWithHooks(ctx context.Context, client *Client, id int, hooks CascadeDeleteFolderHooks) error {
	// Nested-tx path: reuse caller's transaction, no commit/rollback here.
	if inTransaction(client) {
		if hooks.Pre != nil {
			if err := hooks.Pre(ctx, client, id); err != nil {
				return err
			}
		}
		if err := cascadeDeleteFolderOps(ctx, client, id); err != nil {
			return err
		}
		if hooks.Post != nil {
			if err := hooks.Post(ctx, client, id); err != nil {
				return err
			}
		}
		return nil
	}

	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete folder: start tx: %w", err)
	}
	if hooks.Pre != nil {
		if err := hooks.Pre(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete folder: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := cascadeDeleteFolderOps(ctx, tx.Client(), id); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete folder: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if hooks.Post != nil {
		if err := hooks.Post(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete folder: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete folder: commit: %w", err)
	}
	return nil
}

func cascadeDeleteFolderOps(ctx context.Context, client *Client, id int) error {
	// Unlink channels (unlink).
	if err := client.Channel.Update().Where(channel.FolderID(id)).ClearFolderID().Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: unlink channel: %w", err)
	}
	// Delete Folder itself.
	if _, err := client.Folder.Delete().Where(folder.ID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete folder: %w", err)
	}
	return nil
}

// CascadeDeleteFolderBatch deletes multiple Folder entities and all their dependents in a single transaction.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteFolderBatch(ctx context.Context, client *Client, ids []int) error {
	if len(ids) == 0 {
		return nil
	}
	// Nested-tx path: reuse caller's transaction.
	if inTransaction(client) {
		return cascadeDeleteFolderBatchOps(ctx, client, ids)
	}
	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete folder batch: start tx: %w", err)
	}
	if err := cascadeDeleteFolderBatchOps(ctx, tx.Client(), ids); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete folder batch: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete folder batch: commit: %w", err)
	}
	return nil
}

func cascadeDeleteFolderBatchOps(ctx context.Context, client *Client, ids []int) error {
	// Unlink channels (unlink).
	if err := client.Channel.Update().Where(channel.FolderIDIn(ids...)).ClearFolderID().Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: unlink channel: %w", err)
	}
	// Delete Folder entities.
	if _, err := client.Folder.Delete().Where(folder.IDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete folder batch: %w", err)
	}
	return nil
}

// CascadeDeletePostHooks allows injecting business logic around the cascade delete.
// Both hooks run inside the transaction. Return an error to abort and rollback.
type CascadeDeletePostHooks struct {
	// Pre runs before any delete operations.
	Pre func(ctx context.Context, client *Client, id int) error
	// Post runs after all deletes (including the entity itself).
	Post func(ctx context.Context, client *Client, id int) error
}

// CascadeDeletePost deletes a Post and all its dependent entities in a transaction.
func CascadeDeletePost(ctx context.Context, client *Client, id int) error {
	return CascadeDeletePostWithHooks(ctx, client, id, CascadeDeletePostHooks{})
}

// CascadeDeletePostWithHooks deletes a Post and all its dependent entities in a transaction,
// calling the provided hooks inside the transaction boundary.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeletePostWithHooks(ctx context.Context, client *Client, id int, hooks CascadeDeletePostHooks) error {
	// Nested-tx path: reuse caller's transaction, no commit/rollback here.
	if inTransaction(client) {
		if hooks.Pre != nil {
			if err := hooks.Pre(ctx, client, id); err != nil {
				return err
			}
		}
		if err := cascadeDeletePostOps(ctx, client, id); err != nil {
			return err
		}
		if hooks.Post != nil {
			if err := hooks.Post(ctx, client, id); err != nil {
				return err
			}
		}
		return nil
	}

	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete post: start tx: %w", err)
	}
	if hooks.Pre != nil {
		if err := hooks.Pre(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete post: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := cascadeDeletePostOps(ctx, tx.Client(), id); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete post: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if hooks.Post != nil {
		if err := hooks.Post(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete post: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete post: commit: %w", err)
	}
	return nil
}

func cascadeDeletePostOps(ctx context.Context, client *Client, id int) error {
	// Delete comments (O2M leaf).
	if _, err := client.Comment.Delete().Where(comment.PostID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: delete comment: %w", err)
	}
	// Delete tags (M2M through PostTag).
	if _, err := client.PostTag.Delete().Where(posttag.PostID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: delete postTag: %w", err)
	}
	// Delete Post itself.
	if _, err := client.Post.Delete().Where(post.ID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete post: %w", err)
	}
	return nil
}

// CascadeDeletePostBatch deletes multiple Post entities and all their dependents in a single transaction.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeletePostBatch(ctx context.Context, client *Client, ids []int) error {
	if len(ids) == 0 {
		return nil
	}
	// Nested-tx path: reuse caller's transaction.
	if inTransaction(client) {
		return cascadeDeletePostBatchOps(ctx, client, ids)
	}
	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete post batch: start tx: %w", err)
	}
	if err := cascadeDeletePostBatchOps(ctx, tx.Client(), ids); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete post batch: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete post batch: commit: %w", err)
	}
	return nil
}

func cascadeDeletePostBatchOps(ctx context.Context, client *Client, ids []int) error {
	// Delete comments (O2M leaf).
	if _, err := client.Comment.Delete().Where(comment.PostIDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: delete comment: %w", err)
	}
	// Delete tags (M2M through PostTag).
	if _, err := client.PostTag.Delete().Where(posttag.PostIDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: delete postTag: %w", err)
	}
	// Delete Post entities.
	if _, err := client.Post.Delete().Where(post.IDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete post batch: %w", err)
	}
	return nil
}

// CascadeDeleteTeamHooks allows injecting business logic around the cascade delete.
// Both hooks run inside the transaction. Return an error to abort and rollback.
type CascadeDeleteTeamHooks struct {
	// Pre runs before any delete operations.
	Pre func(ctx context.Context, client *Client, id int) error
	// Post runs after all deletes (including the entity itself).
	Post func(ctx context.Context, client *Client, id int) error
}

// CascadeDeleteTeam deletes a Team and all its dependent entities in a transaction.
func CascadeDeleteTeam(ctx context.Context, client *Client, id int) error {
	return CascadeDeleteTeamWithHooks(ctx, client, id, CascadeDeleteTeamHooks{})
}

// CascadeDeleteTeamWithHooks deletes a Team and all its dependent entities in a transaction,
// calling the provided hooks inside the transaction boundary.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteTeamWithHooks(ctx context.Context, client *Client, id int, hooks CascadeDeleteTeamHooks) error {
	// Nested-tx path: reuse caller's transaction, no commit/rollback here.
	if inTransaction(client) {
		if hooks.Pre != nil {
			if err := hooks.Pre(ctx, client, id); err != nil {
				return err
			}
		}
		if err := cascadeDeleteTeamOps(ctx, client, id); err != nil {
			return err
		}
		if hooks.Post != nil {
			if err := hooks.Post(ctx, client, id); err != nil {
				return err
			}
		}
		return nil
	}

	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete team: start tx: %w", err)
	}
	if hooks.Pre != nil {
		if err := hooks.Pre(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete team: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := cascadeDeleteTeamOps(ctx, tx.Client(), id); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete team: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if hooks.Post != nil {
		if err := hooks.Post(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete team: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete team: commit: %w", err)
	}
	return nil
}

func cascadeDeleteTeamOps(ctx context.Context, client *Client, id int) error {
	// Delete members (O2M leaf).
	if _, err := client.Member.Delete().Where(member.TeamID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: delete member: %w", err)
	}
	// Delete Team itself.
	if _, err := client.Team.Delete().Where(team.ID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete team: %w", err)
	}
	return nil
}

// CascadeDeleteTeamBatch deletes multiple Team entities and all their dependents in a single transaction.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteTeamBatch(ctx context.Context, client *Client, ids []int) error {
	if len(ids) == 0 {
		return nil
	}
	// Nested-tx path: reuse caller's transaction.
	if inTransaction(client) {
		return cascadeDeleteTeamBatchOps(ctx, client, ids)
	}
	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete team batch: start tx: %w", err)
	}
	if err := cascadeDeleteTeamBatchOps(ctx, tx.Client(), ids); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete team batch: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete team batch: commit: %w", err)
	}
	return nil
}

func cascadeDeleteTeamBatchOps(ctx context.Context, client *Client, ids []int) error {
	// Delete members (O2M leaf).
	if _, err := client.Member.Delete().Where(member.TeamIDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: delete member: %w", err)
	}
	// Delete Team entities.
	if _, err := client.Team.Delete().Where(team.IDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete team batch: %w", err)
	}
	return nil
}

// CascadeDeleteUserHooks allows injecting business logic around the cascade delete.
// Both hooks run inside the transaction. Return an error to abort and rollback.
type CascadeDeleteUserHooks struct {
	// Pre runs before any delete operations.
	Pre func(ctx context.Context, client *Client, id int) error
	// Post runs after all deletes (including the entity itself).
	Post func(ctx context.Context, client *Client, id int) error
}

// CascadeDeleteUser deletes a User and all its dependent entities in a transaction.
func CascadeDeleteUser(ctx context.Context, client *Client, id int) error {
	return CascadeDeleteUserWithHooks(ctx, client, id, CascadeDeleteUserHooks{})
}

// CascadeDeleteUserWithHooks deletes a User and all its dependent entities in a transaction,
// calling the provided hooks inside the transaction boundary.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteUserWithHooks(ctx context.Context, client *Client, id int, hooks CascadeDeleteUserHooks) error {
	// Nested-tx path: reuse caller's transaction, no commit/rollback here.
	if inTransaction(client) {
		if hooks.Pre != nil {
			if err := hooks.Pre(ctx, client, id); err != nil {
				return err
			}
		}
		if err := cascadeDeleteUserOps(ctx, client, id); err != nil {
			return err
		}
		if hooks.Post != nil {
			if err := hooks.Post(ctx, client, id); err != nil {
				return err
			}
		}
		return nil
	}

	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete user: start tx: %w", err)
	}
	if hooks.Pre != nil {
		if err := hooks.Pre(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete user: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := cascadeDeleteUserOps(ctx, tx.Client(), id); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete user: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if hooks.Post != nil {
		if err := hooks.Post(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete user: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete user: commit: %w", err)
	}
	return nil
}

func cascadeDeleteUserOps(ctx context.Context, client *Client, id int) error {
	// Cascade into posts (cascade).
	postIDs, err := client.Post.Query().Where(post.AuthorID(id)).IDs(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete: query post: %w", err)
	}
	if len(postIDs) > 0 {
		// Delete Post.comments (leaf).
		if _, err := client.Comment.Delete().Where(comment.PostIDIn(postIDs...)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete comment: %w", err)
		}
		// Delete tags (M2M through PostTag).
		if _, err := client.PostTag.Delete().Where(posttag.PostIDIn(postIDs...)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete postTag: %w", err)
		}
		if _, err := client.Post.Delete().Where(post.AuthorID(id)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete post: %w", err)
		}
	}
	// Delete profile (O2M leaf).
	if _, err := client.Profile.Delete().Where(profile.UserID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: delete profile: %w", err)
	}
	// Delete User itself.
	if _, err := client.User.Delete().Where(user.ID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete user: %w", err)
	}
	return nil
}

// CascadeDeleteUserBatch deletes multiple User entities and all their dependents in a single transaction.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteUserBatch(ctx context.Context, client *Client, ids []int) error {
	if len(ids) == 0 {
		return nil
	}
	// Nested-tx path: reuse caller's transaction.
	if inTransaction(client) {
		return cascadeDeleteUserBatchOps(ctx, client, ids)
	}
	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete user batch: start tx: %w", err)
	}
	if err := cascadeDeleteUserBatchOps(ctx, tx.Client(), ids); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete user batch: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete user batch: commit: %w", err)
	}
	return nil
}

func cascadeDeleteUserBatchOps(ctx context.Context, client *Client, ids []int) error {
	// Cascade into posts (cascade).
	postIDs, err := client.Post.Query().Where(post.AuthorIDIn(ids...)).IDs(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete: query post: %w", err)
	}
	if len(postIDs) > 0 {
		// Delete Post.comments (leaf).
		if _, err := client.Comment.Delete().Where(comment.PostIDIn(postIDs...)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete comment: %w", err)
		}
		// Delete tags (M2M through PostTag).
		if _, err := client.PostTag.Delete().Where(posttag.PostIDIn(postIDs...)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete postTag: %w", err)
		}
		if _, err := client.Post.Delete().Where(post.AuthorIDIn(ids...)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete post: %w", err)
		}
	}
	// Delete profile (O2M leaf).
	if _, err := client.Profile.Delete().Where(profile.UserIDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete: delete profile: %w", err)
	}
	// Delete User entities.
	if _, err := client.User.Delete().Where(user.IDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete user batch: %w", err)
	}
	return nil
}

// CascadeDeleteWorkspaceHooks allows injecting business logic around the cascade delete.
// Both hooks run inside the transaction. Return an error to abort and rollback.
type CascadeDeleteWorkspaceHooks struct {
	// Pre runs before any delete operations.
	Pre func(ctx context.Context, client *Client, id int) error
	// Post runs after all deletes (including the entity itself).
	Post func(ctx context.Context, client *Client, id int) error
}

// CascadeDeleteWorkspace deletes a Workspace and all its dependent entities in a transaction.
func CascadeDeleteWorkspace(ctx context.Context, client *Client, id int) error {
	return CascadeDeleteWorkspaceWithHooks(ctx, client, id, CascadeDeleteWorkspaceHooks{})
}

// CascadeDeleteWorkspaceWithHooks deletes a Workspace and all its dependent entities in a transaction,
// calling the provided hooks inside the transaction boundary.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteWorkspaceWithHooks(ctx context.Context, client *Client, id int, hooks CascadeDeleteWorkspaceHooks) error {
	// Nested-tx path: reuse caller's transaction, no commit/rollback here.
	if inTransaction(client) {
		if hooks.Pre != nil {
			if err := hooks.Pre(ctx, client, id); err != nil {
				return err
			}
		}
		if err := cascadeDeleteWorkspaceOps(ctx, client, id); err != nil {
			return err
		}
		if hooks.Post != nil {
			if err := hooks.Post(ctx, client, id); err != nil {
				return err
			}
		}
		return nil
	}

	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete workspace: start tx: %w", err)
	}
	if hooks.Pre != nil {
		if err := hooks.Pre(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete workspace: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := cascadeDeleteWorkspaceOps(ctx, tx.Client(), id); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete workspace: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if hooks.Post != nil {
		if err := hooks.Post(ctx, tx.Client(), id); err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				return fmt.Errorf("cascade delete workspace: rollback: %w (original: %w)", rerr, err)
			}
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete workspace: commit: %w", err)
	}
	return nil
}

func cascadeDeleteWorkspaceOps(ctx context.Context, client *Client, id int) error {
	// Cascade into folders (cascade).
	folderIDs, err := client.Folder.Query().Where(folder.WorkspaceID(id)).IDs(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete: query folder: %w", err)
	}
	if len(folderIDs) > 0 {
		// Unlink channels (unlink).
		if err := client.Channel.Update().Where(channel.FolderIDIn(folderIDs...)).ClearFolderID().Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: unlink channel: %w", err)
		}
		if _, err := client.Folder.Delete().Where(folder.WorkspaceID(id)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete folder: %w", err)
		}
	}
	// Cascade into docs (cascade).
	docIDs, err := client.Doc.Query().Where(doc.WorkspaceID(id)).IDs(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete: query doc: %w", err)
	}
	if len(docIDs) > 0 {
		// Soft-delete notes (soft-delete via archived_at).
		if err := client.Note.Update().Where(note.DocIDIn(docIDs...)).SetArchivedAt(time.Now()).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: soft-delete note: %w", err)
		}
		if _, err := client.Doc.Delete().Where(doc.WorkspaceID(id)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete doc: %w", err)
		}
	}
	// Delete Workspace itself.
	if _, err := client.Workspace.Delete().Where(workspace.ID(id)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete workspace: %w", err)
	}
	return nil
}

// CascadeDeleteWorkspaceBatch deletes multiple Workspace entities and all their dependents in a single transaction.
//
// If client is already a transactional client (obtained via tx.Client()),
// the existing transaction is reused — no new transaction is started and
// the caller retains ownership of commit/rollback.
func CascadeDeleteWorkspaceBatch(ctx context.Context, client *Client, ids []int) error {
	if len(ids) == 0 {
		return nil
	}
	// Nested-tx path: reuse caller's transaction.
	if inTransaction(client) {
		return cascadeDeleteWorkspaceBatchOps(ctx, client, ids)
	}
	// Standalone path: own the transaction.
	tx, err := client.Tx(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete workspace batch: start tx: %w", err)
	}
	if err := cascadeDeleteWorkspaceBatchOps(ctx, tx.Client(), ids); err != nil {
		if rerr := tx.Rollback(); rerr != nil {
			return fmt.Errorf("cascade delete workspace batch: rollback: %w (original: %w)", rerr, err)
		}
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cascade delete workspace batch: commit: %w", err)
	}
	return nil
}

func cascadeDeleteWorkspaceBatchOps(ctx context.Context, client *Client, ids []int) error {
	// Cascade into folders (cascade).
	folderIDs, err := client.Folder.Query().Where(folder.WorkspaceIDIn(ids...)).IDs(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete: query folder: %w", err)
	}
	if len(folderIDs) > 0 {
		// Unlink channels (unlink).
		if err := client.Channel.Update().Where(channel.FolderIDIn(folderIDs...)).ClearFolderID().Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: unlink channel: %w", err)
		}
		if _, err := client.Folder.Delete().Where(folder.WorkspaceIDIn(ids...)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete folder: %w", err)
		}
	}
	// Cascade into docs (cascade).
	docIDs, err := client.Doc.Query().Where(doc.WorkspaceIDIn(ids...)).IDs(ctx)
	if err != nil {
		return fmt.Errorf("cascade delete: query doc: %w", err)
	}
	if len(docIDs) > 0 {
		// Soft-delete notes (soft-delete via archived_at).
		if err := client.Note.Update().Where(note.DocIDIn(docIDs...)).SetArchivedAt(time.Now()).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: soft-delete note: %w", err)
		}
		if _, err := client.Doc.Delete().Where(doc.WorkspaceIDIn(ids...)).Exec(ctx); err != nil {
			return fmt.Errorf("cascade delete: delete doc: %w", err)
		}
	}
	// Delete Workspace entities.
	if _, err := client.Workspace.Delete().Where(workspace.IDIn(ids...)).Exec(ctx); err != nil {
		return fmt.Errorf("cascade delete workspace batch: %w", err)
	}
	return nil
}
