// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/entx/testent/ent/doc"
	"github.com/khanakia/entx/testent/ent/note"
	"github.com/khanakia/entx/testent/ent/predicate"
	"github.com/khanakia/entx/testent/ent/workspace"
)

// DocQuery is the builder for querying Doc entities.
type DocQuery struct {
	config
	ctx           *QueryContext
	order         []doc.OrderOption
	inters        []Interceptor
	predicates    []predicate.Doc
	withWorkspace *WorkspaceQuery
	withNotes     *NoteQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DocQuery builder.
func (_q *DocQuery) Where(ps ...predicate.Doc) *DocQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DocQuery) Limit(limit int) *DocQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DocQuery) Offset(offset int) *DocQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DocQuery) Unique(unique bool) *DocQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DocQuery) Order(o ...doc.OrderOption) *DocQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWorkspace chains the current query on the "workspace" edge.
func (_q *DocQuery) QueryWorkspace() *WorkspaceQuery {
	query := (&WorkspaceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(doc.Table, doc.FieldID, selector),
			sqlgraph.To(workspace.Table, workspace.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, doc.WorkspaceTable, doc.WorkspaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNotes chains the current query on the "notes" edge.
func (_q *DocQuery) QueryNotes() *NoteQuery {
	query := (&NoteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(doc.Table, doc.FieldID, selector),
			sqlgraph.To(note.Table, note.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, doc.NotesTable, doc.NotesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Doc entity from the query.
// Returns a *NotFoundError when no Doc was found.
func (_q *DocQuery) First(ctx context.Context) (*Doc, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{doc.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DocQuery) FirstX(ctx context.Context) *Doc {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Doc ID from the query.
// Returns a *NotFoundError when no Doc ID was found.
func (_q *DocQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{doc.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DocQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Doc entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Doc entity is found.
// Returns a *NotFoundError when no Doc entities are found.
func (_q *DocQuery) Only(ctx context.Context) (*Doc, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{doc.Label}
	default:
		return nil, &NotSingularError{doc.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DocQuery) OnlyX(ctx context.Context) *Doc {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Doc ID in the query.
// Returns a *NotSingularError when more than one Doc ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DocQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{doc.Label}
	default:
		err = &NotSingularError{doc.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DocQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Docs.
func (_q *DocQuery) All(ctx context.Context) ([]*Doc, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Doc, *DocQuery]()
	return withInterceptors[[]*Doc](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DocQuery) AllX(ctx context.Context) []*Doc {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Doc IDs.
func (_q *DocQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(doc.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DocQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DocQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DocQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DocQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DocQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DocQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DocQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DocQuery) Clone() *DocQuery {
	if _q == nil {
		return nil
	}
	return &DocQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]doc.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Doc{}, _q.predicates...),
		withWorkspace: _q.withWorkspace.Clone(),
		withNotes:     _q.withNotes.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWorkspace tells the query-builder to eager-load the nodes that are connected to
// the "workspace" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DocQuery) WithWorkspace(opts ...func(*WorkspaceQuery)) *DocQuery {
	query := (&WorkspaceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorkspace = query
	return _q
}

// WithNotes tells the query-builder to eager-load the nodes that are connected to
// the "notes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DocQuery) WithNotes(opts ...func(*NoteQuery)) *DocQuery {
	query := (&NoteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNotes = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Doc.Query().
//		GroupBy(doc.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DocQuery) GroupBy(field string, fields ...string) *DocGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DocGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = doc.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Doc.Query().
//		Select(doc.FieldTitle).
//		Scan(ctx, &v)
func (_q *DocQuery) Select(fields ...string) *DocSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DocSelect{DocQuery: _q}
	sbuild.label = doc.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DocSelect configured with the given aggregations.
func (_q *DocQuery) Aggregate(fns ...AggregateFunc) *DocSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DocQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !doc.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DocQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Doc, error) {
	var (
		nodes       = []*Doc{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withWorkspace != nil,
			_q.withNotes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Doc).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Doc{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWorkspace; query != nil {
		if err := _q.loadWorkspace(ctx, query, nodes, nil,
			func(n *Doc, e *Workspace) { n.Edges.Workspace = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNotes; query != nil {
		if err := _q.loadNotes(ctx, query, nodes,
			func(n *Doc) { n.Edges.Notes = []*Note{} },
			func(n *Doc, e *Note) { n.Edges.Notes = append(n.Edges.Notes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DocQuery) loadWorkspace(ctx context.Context, query *WorkspaceQuery, nodes []*Doc, init func(*Doc), assign func(*Doc, *Workspace)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Doc)
	for i := range nodes {
		fk := nodes[i].WorkspaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workspace.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workspace_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DocQuery) loadNotes(ctx context.Context, query *NoteQuery, nodes []*Doc, init func(*Doc), assign func(*Doc, *Note)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Doc)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(note.FieldDocID)
	}
	query.Where(predicate.Note(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(doc.NotesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DocID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "doc_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DocQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DocQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(doc.Table, doc.Columns, sqlgraph.NewFieldSpec(doc.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, doc.FieldID)
		for i := range fields {
			if fields[i] != doc.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withWorkspace != nil {
			_spec.Node.AddColumnOnce(doc.FieldWorkspaceID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DocQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(doc.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = doc.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DocGroupBy is the group-by builder for Doc entities.
type DocGroupBy struct {
	selector
	build *DocQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DocGroupBy) Aggregate(fns ...AggregateFunc) *DocGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DocGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DocQuery, *DocGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DocGroupBy) sqlScan(ctx context.Context, root *DocQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DocSelect is the builder for selecting fields of Doc entities.
type DocSelect struct {
	*DocQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DocSelect) Aggregate(fns ...AggregateFunc) *DocSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DocSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DocQuery, *DocSelect](ctx, _s.DocQuery, _s, _s.inters, v)
}

func (_s *DocSelect) sqlScan(ctx context.Context, root *DocQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
