// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/entx/testent/ent/doc"
	"github.com/khanakia/entx/testent/ent/note"
	"github.com/khanakia/entx/testent/ent/predicate"
)

// NoteUpdate is the builder for updating Note entities.
type NoteUpdate struct {
	config
	hooks    []Hook
	mutation *NoteMutation
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdate) Where(ps ...predicate.Note) *NoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBody sets the "body" field.
func (_u *NoteUpdate) SetBody(v string) *NoteUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableBody(v *string) *NoteUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetDocID sets the "doc_id" field.
func (_u *NoteUpdate) SetDocID(v int) *NoteUpdate {
	_u.mutation.SetDocID(v)
	return _u
}

// SetNillableDocID sets the "doc_id" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableDocID(v *int) *NoteUpdate {
	if v != nil {
		_u.SetDocID(*v)
	}
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *NoteUpdate) SetArchivedAt(v time.Time) *NoteUpdate {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableArchivedAt(v *time.Time) *NoteUpdate {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *NoteUpdate) ClearArchivedAt() *NoteUpdate {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetDoc sets the "doc" edge to the Doc entity.
func (_u *NoteUpdate) SetDoc(v *Doc) *NoteUpdate {
	return _u.SetDocID(v.ID)
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdate) Mutation() *NoteMutation {
	return _u.mutation
}

// ClearDoc clears the "doc" edge to the Doc entity.
func (_u *NoteUpdate) ClearDoc() *NoteUpdate {
	_u.mutation.ClearDoc()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteUpdate) check() error {
	if _u.mutation.DocCleared() && len(_u.mutation.DocIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.doc"`)
	}
	return nil
}

func (_u *NoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(note.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(note.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(note.FieldArchivedAt, field.TypeTime)
	}
	if _u.mutation.DocCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.DocTable,
			Columns: []string{note.DocColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doc.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.DocTable,
			Columns: []string{note.DocColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doc.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NoteUpdateOne is the builder for updating a single Note entity.
type NoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoteMutation
}

// SetBody sets the "body" field.
func (_u *NoteUpdateOne) SetBody(v string) *NoteUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableBody(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetDocID sets the "doc_id" field.
func (_u *NoteUpdateOne) SetDocID(v int) *NoteUpdateOne {
	_u.mutation.SetDocID(v)
	return _u
}

// SetNillableDocID sets the "doc_id" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableDocID(v *int) *NoteUpdateOne {
	if v != nil {
		_u.SetDocID(*v)
	}
	return _u
}

// SetArchivedAt sets the "archived_at" field.
func (_u *NoteUpdateOne) SetArchivedAt(v time.Time) *NoteUpdateOne {
	_u.mutation.SetArchivedAt(v)
	return _u
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableArchivedAt(v *time.Time) *NoteUpdateOne {
	if v != nil {
		_u.SetArchivedAt(*v)
	}
	return _u
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (_u *NoteUpdateOne) ClearArchivedAt() *NoteUpdateOne {
	_u.mutation.ClearArchivedAt()
	return _u
}

// SetDoc sets the "doc" edge to the Doc entity.
func (_u *NoteUpdateOne) SetDoc(v *Doc) *NoteUpdateOne {
	return _u.SetDocID(v.ID)
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdateOne) Mutation() *NoteMutation {
	return _u.mutation
}

// ClearDoc clears the "doc" edge to the Doc entity.
func (_u *NoteUpdateOne) ClearDoc() *NoteUpdateOne {
	_u.mutation.ClearDoc()
	return _u
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdateOne) Where(ps ...predicate.Note) *NoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NoteUpdateOne) Select(field string, fields ...string) *NoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Note entity.
func (_u *NoteUpdateOne) Save(ctx context.Context) (*Note, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdateOne) SaveX(ctx context.Context) *Note {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NoteUpdateOne) check() error {
	if _u.mutation.DocCleared() && len(_u.mutation.DocIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Note.doc"`)
	}
	return nil
}

func (_u *NoteUpdateOne) sqlSave(ctx context.Context) (_node *Note, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Note.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, note.FieldID)
		for _, f := range fields {
			if !note.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != note.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(note.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ArchivedAt(); ok {
		_spec.SetField(note.FieldArchivedAt, field.TypeTime, value)
	}
	if _u.mutation.ArchivedAtCleared() {
		_spec.ClearField(note.FieldArchivedAt, field.TypeTime)
	}
	if _u.mutation.DocCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.DocTable,
			Columns: []string{note.DocColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doc.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   note.DocTable,
			Columns: []string{note.DocColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doc.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Note{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
