// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/entx/testent/ent/article"
	"github.com/khanakia/entx/testent/ent/predicate"
	"github.com/khanakia/entx/testent/ent/revision"
)

// RevisionUpdate is the builder for updating Revision entities.
type RevisionUpdate struct {
	config
	hooks    []Hook
	mutation *RevisionMutation
}

// Where appends a list predicates to the RevisionUpdate builder.
func (_u *RevisionUpdate) Where(ps ...predicate.Revision) *RevisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBody sets the "body" field.
func (_u *RevisionUpdate) SetBody(v string) *RevisionUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *RevisionUpdate) SetNillableBody(v *string) *RevisionUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RevisionUpdate) SetVersion(v int) *RevisionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RevisionUpdate) SetNillableVersion(v *int) *RevisionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RevisionUpdate) AddVersion(v int) *RevisionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *RevisionUpdate) SetArticleID(v int) *RevisionUpdate {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *RevisionUpdate) SetNillableArticleID(v *int) *RevisionUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RevisionUpdate) SetDeletedAt(v time.Time) *RevisionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RevisionUpdate) SetNillableDeletedAt(v *time.Time) *RevisionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RevisionUpdate) ClearDeletedAt() *RevisionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *RevisionUpdate) SetArticle(v *Article) *RevisionUpdate {
	return _u.SetArticleID(v.ID)
}

// Mutation returns the RevisionMutation object of the builder.
func (_u *RevisionUpdate) Mutation() *RevisionMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *RevisionUpdate) ClearArticle() *RevisionUpdate {
	_u.mutation.ClearArticle()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RevisionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RevisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RevisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RevisionUpdate) check() error {
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Revision.article"`)
	}
	return nil
}

func (_u *RevisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(revision.Table, revision.Columns, sqlgraph.NewFieldSpec(revision.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(revision.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(revision.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(revision.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(revision.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(revision.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   revision.ArticleTable,
			Columns: []string{revision.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   revision.ArticleTable,
			Columns: []string{revision.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RevisionUpdateOne is the builder for updating a single Revision entity.
type RevisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RevisionMutation
}

// SetBody sets the "body" field.
func (_u *RevisionUpdateOne) SetBody(v string) *RevisionUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *RevisionUpdateOne) SetNillableBody(v *string) *RevisionUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RevisionUpdateOne) SetVersion(v int) *RevisionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RevisionUpdateOne) SetNillableVersion(v *int) *RevisionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RevisionUpdateOne) AddVersion(v int) *RevisionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *RevisionUpdateOne) SetArticleID(v int) *RevisionUpdateOne {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *RevisionUpdateOne) SetNillableArticleID(v *int) *RevisionUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RevisionUpdateOne) SetDeletedAt(v time.Time) *RevisionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RevisionUpdateOne) SetNillableDeletedAt(v *time.Time) *RevisionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RevisionUpdateOne) ClearDeletedAt() *RevisionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *RevisionUpdateOne) SetArticle(v *Article) *RevisionUpdateOne {
	return _u.SetArticleID(v.ID)
}

// Mutation returns the RevisionMutation object of the builder.
func (_u *RevisionUpdateOne) Mutation() *RevisionMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *RevisionUpdateOne) ClearArticle() *RevisionUpdateOne {
	_u.mutation.ClearArticle()
	return _u
}

// Where appends a list predicates to the RevisionUpdate builder.
func (_u *RevisionUpdateOne) Where(ps ...predicate.Revision) *RevisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RevisionUpdateOne) Select(field string, fields ...string) *RevisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Revision entity.
func (_u *RevisionUpdateOne) Save(ctx context.Context) (*Revision, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RevisionUpdateOne) SaveX(ctx context.Context) *Revision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RevisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RevisionUpdateOne) check() error {
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Revision.article"`)
	}
	return nil
}

func (_u *RevisionUpdateOne) sqlSave(ctx context.Context) (_node *Revision, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(revision.Table, revision.Columns, sqlgraph.NewFieldSpec(revision.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Revision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, revision.FieldID)
		for _, f := range fields {
			if !revision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != revision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(revision.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(revision.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(revision.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(revision.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(revision.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   revision.ArticleTable,
			Columns: []string{revision.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   revision.ArticleTable,
			Columns: []string{revision.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Revision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{revision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
