// Code generated by ent, DO NOT EDIT.

package note

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the note type in the database.
	Label = "note"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldDocID holds the string denoting the doc_id field in the database.
	FieldDocID = "doc_id"
	// FieldArchivedAt holds the string denoting the archived_at field in the database.
	FieldArchivedAt = "archived_at"
	// EdgeDoc holds the string denoting the doc edge name in mutations.
	EdgeDoc = "doc"
	// Table holds the table name of the note in the database.
	Table = "notes"
	// DocTable is the table that holds the doc relation/edge.
	DocTable = "notes"
	// DocInverseTable is the table name for the Doc entity.
	// It exists in this package in order to avoid circular dependency with the "doc" package.
	DocInverseTable = "docs"
	// DocColumn is the table column denoting the doc relation/edge.
	DocColumn = "doc_id"
)

// Columns holds all SQL columns for note fields.
var Columns = []string{
	FieldID,
	FieldBody,
	FieldDocID,
	FieldArchivedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Note queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByDocID orders the results by the doc_id field.
func ByDocID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocID, opts...).ToFunc()
}

// ByArchivedAt orders the results by the archived_at field.
func ByArchivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchivedAt, opts...).ToFunc()
}

// ByDocField orders the results by doc field.
func ByDocField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDocStep(), sql.OrderByField(field, opts...))
	}
}
func newDocStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DocInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DocTable, DocColumn),
	)
}
