// Code generated by ent, DO NOT EDIT.

package sourcelink

import (
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/entx/entpoly/examples/morphstring/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldLTE(FieldID, id))
}

// SourceableID applies equality check predicate on the "sourceable_id" field. It's identical to SourceableIDEQ.
func SourceableID(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEQ(FieldSourceableID, v))
}

// SourceableType applies equality check predicate on the "sourceable_type" field. It's identical to SourceableTypeEQ.
func SourceableType(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEQ(FieldSourceableType, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEQ(FieldURL, v))
}

// SourceableIDEQ applies the EQ predicate on the "sourceable_id" field.
func SourceableIDEQ(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEQ(FieldSourceableID, v))
}

// SourceableIDNEQ applies the NEQ predicate on the "sourceable_id" field.
func SourceableIDNEQ(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNEQ(FieldSourceableID, v))
}

// SourceableIDIn applies the In predicate on the "sourceable_id" field.
func SourceableIDIn(vs ...string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldIn(FieldSourceableID, vs...))
}

// SourceableIDNotIn applies the NotIn predicate on the "sourceable_id" field.
func SourceableIDNotIn(vs ...string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNotIn(FieldSourceableID, vs...))
}

// SourceableIDGT applies the GT predicate on the "sourceable_id" field.
func SourceableIDGT(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldGT(FieldSourceableID, v))
}

// SourceableIDGTE applies the GTE predicate on the "sourceable_id" field.
func SourceableIDGTE(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldGTE(FieldSourceableID, v))
}

// SourceableIDLT applies the LT predicate on the "sourceable_id" field.
func SourceableIDLT(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldLT(FieldSourceableID, v))
}

// SourceableIDLTE applies the LTE predicate on the "sourceable_id" field.
func SourceableIDLTE(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldLTE(FieldSourceableID, v))
}

// SourceableIDContains applies the Contains predicate on the "sourceable_id" field.
func SourceableIDContains(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldContains(FieldSourceableID, v))
}

// SourceableIDHasPrefix applies the HasPrefix predicate on the "sourceable_id" field.
func SourceableIDHasPrefix(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldHasPrefix(FieldSourceableID, v))
}

// SourceableIDHasSuffix applies the HasSuffix predicate on the "sourceable_id" field.
func SourceableIDHasSuffix(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldHasSuffix(FieldSourceableID, v))
}

// SourceableIDIsNil applies the IsNil predicate on the "sourceable_id" field.
func SourceableIDIsNil() predicate.SourceLink {
	return predicate.SourceLink(sql.FieldIsNull(FieldSourceableID))
}

// SourceableIDNotNil applies the NotNil predicate on the "sourceable_id" field.
func SourceableIDNotNil() predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNotNull(FieldSourceableID))
}

// SourceableIDEqualFold applies the EqualFold predicate on the "sourceable_id" field.
func SourceableIDEqualFold(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEqualFold(FieldSourceableID, v))
}

// SourceableIDContainsFold applies the ContainsFold predicate on the "sourceable_id" field.
func SourceableIDContainsFold(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldContainsFold(FieldSourceableID, v))
}

// SourceableTypeEQ applies the EQ predicate on the "sourceable_type" field.
func SourceableTypeEQ(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEQ(FieldSourceableType, v))
}

// SourceableTypeNEQ applies the NEQ predicate on the "sourceable_type" field.
func SourceableTypeNEQ(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNEQ(FieldSourceableType, v))
}

// SourceableTypeIn applies the In predicate on the "sourceable_type" field.
func SourceableTypeIn(vs ...string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldIn(FieldSourceableType, vs...))
}

// SourceableTypeNotIn applies the NotIn predicate on the "sourceable_type" field.
func SourceableTypeNotIn(vs ...string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNotIn(FieldSourceableType, vs...))
}

// SourceableTypeGT applies the GT predicate on the "sourceable_type" field.
func SourceableTypeGT(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldGT(FieldSourceableType, v))
}

// SourceableTypeGTE applies the GTE predicate on the "sourceable_type" field.
func SourceableTypeGTE(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldGTE(FieldSourceableType, v))
}

// SourceableTypeLT applies the LT predicate on the "sourceable_type" field.
func SourceableTypeLT(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldLT(FieldSourceableType, v))
}

// SourceableTypeLTE applies the LTE predicate on the "sourceable_type" field.
func SourceableTypeLTE(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldLTE(FieldSourceableType, v))
}

// SourceableTypeContains applies the Contains predicate on the "sourceable_type" field.
func SourceableTypeContains(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldContains(FieldSourceableType, v))
}

// SourceableTypeHasPrefix applies the HasPrefix predicate on the "sourceable_type" field.
func SourceableTypeHasPrefix(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldHasPrefix(FieldSourceableType, v))
}

// SourceableTypeHasSuffix applies the HasSuffix predicate on the "sourceable_type" field.
func SourceableTypeHasSuffix(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldHasSuffix(FieldSourceableType, v))
}

// SourceableTypeIsNil applies the IsNil predicate on the "sourceable_type" field.
func SourceableTypeIsNil() predicate.SourceLink {
	return predicate.SourceLink(sql.FieldIsNull(FieldSourceableType))
}

// SourceableTypeNotNil applies the NotNil predicate on the "sourceable_type" field.
func SourceableTypeNotNil() predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNotNull(FieldSourceableType))
}

// SourceableTypeEqualFold applies the EqualFold predicate on the "sourceable_type" field.
func SourceableTypeEqualFold(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEqualFold(FieldSourceableType, v))
}

// SourceableTypeContainsFold applies the ContainsFold predicate on the "sourceable_type" field.
func SourceableTypeContainsFold(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldContainsFold(FieldSourceableType, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.SourceLink {
	return predicate.SourceLink(sql.FieldContainsFold(FieldURL, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SourceLink) predicate.SourceLink {
	return predicate.SourceLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SourceLink) predicate.SourceLink {
	return predicate.SourceLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SourceLink) predicate.SourceLink {
	return predicate.SourceLink(sql.NotPredicates(p))
}
