// Code generated by ent, DO NOT EDIT.

package image

import (
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/entx/entpoly/examples/basic/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldID, id))
}

// ImageableID applies equality check predicate on the "imageable_id" field. It's identical to ImageableIDEQ.
func ImageableID(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldImageableID, v))
}

// ImageableType applies equality check predicate on the "imageable_type" field. It's identical to ImageableTypeEQ.
func ImageableType(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldImageableType, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldURL, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldHeight, v))
}

// ImageableIDEQ applies the EQ predicate on the "imageable_id" field.
func ImageableIDEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldImageableID, v))
}

// ImageableIDNEQ applies the NEQ predicate on the "imageable_id" field.
func ImageableIDNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldImageableID, v))
}

// ImageableIDIn applies the In predicate on the "imageable_id" field.
func ImageableIDIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldImageableID, vs...))
}

// ImageableIDNotIn applies the NotIn predicate on the "imageable_id" field.
func ImageableIDNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldImageableID, vs...))
}

// ImageableIDGT applies the GT predicate on the "imageable_id" field.
func ImageableIDGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldImageableID, v))
}

// ImageableIDGTE applies the GTE predicate on the "imageable_id" field.
func ImageableIDGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldImageableID, v))
}

// ImageableIDLT applies the LT predicate on the "imageable_id" field.
func ImageableIDLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldImageableID, v))
}

// ImageableIDLTE applies the LTE predicate on the "imageable_id" field.
func ImageableIDLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldImageableID, v))
}

// ImageableIDContains applies the Contains predicate on the "imageable_id" field.
func ImageableIDContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldImageableID, v))
}

// ImageableIDHasPrefix applies the HasPrefix predicate on the "imageable_id" field.
func ImageableIDHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldImageableID, v))
}

// ImageableIDHasSuffix applies the HasSuffix predicate on the "imageable_id" field.
func ImageableIDHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldImageableID, v))
}

// ImageableIDIsNil applies the IsNil predicate on the "imageable_id" field.
func ImageableIDIsNil() predicate.Image {
	return predicate.Image(sql.FieldIsNull(FieldImageableID))
}

// ImageableIDNotNil applies the NotNil predicate on the "imageable_id" field.
func ImageableIDNotNil() predicate.Image {
	return predicate.Image(sql.FieldNotNull(FieldImageableID))
}

// ImageableIDEqualFold applies the EqualFold predicate on the "imageable_id" field.
func ImageableIDEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldImageableID, v))
}

// ImageableIDContainsFold applies the ContainsFold predicate on the "imageable_id" field.
func ImageableIDContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldImageableID, v))
}

// ImageableTypeEQ applies the EQ predicate on the "imageable_type" field.
func ImageableTypeEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldImageableType, v))
}

// ImageableTypeNEQ applies the NEQ predicate on the "imageable_type" field.
func ImageableTypeNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldImageableType, v))
}

// ImageableTypeIn applies the In predicate on the "imageable_type" field.
func ImageableTypeIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldImageableType, vs...))
}

// ImageableTypeNotIn applies the NotIn predicate on the "imageable_type" field.
func ImageableTypeNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldImageableType, vs...))
}

// ImageableTypeGT applies the GT predicate on the "imageable_type" field.
func ImageableTypeGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldImageableType, v))
}

// ImageableTypeGTE applies the GTE predicate on the "imageable_type" field.
func ImageableTypeGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldImageableType, v))
}

// ImageableTypeLT applies the LT predicate on the "imageable_type" field.
func ImageableTypeLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldImageableType, v))
}

// ImageableTypeLTE applies the LTE predicate on the "imageable_type" field.
func ImageableTypeLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldImageableType, v))
}

// ImageableTypeContains applies the Contains predicate on the "imageable_type" field.
func ImageableTypeContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldImageableType, v))
}

// ImageableTypeHasPrefix applies the HasPrefix predicate on the "imageable_type" field.
func ImageableTypeHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldImageableType, v))
}

// ImageableTypeHasSuffix applies the HasSuffix predicate on the "imageable_type" field.
func ImageableTypeHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldImageableType, v))
}

// ImageableTypeIsNil applies the IsNil predicate on the "imageable_type" field.
func ImageableTypeIsNil() predicate.Image {
	return predicate.Image(sql.FieldIsNull(FieldImageableType))
}

// ImageableTypeNotNil applies the NotNil predicate on the "imageable_type" field.
func ImageableTypeNotNil() predicate.Image {
	return predicate.Image(sql.FieldNotNull(FieldImageableType))
}

// ImageableTypeEqualFold applies the EqualFold predicate on the "imageable_type" field.
func ImageableTypeEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldImageableType, v))
}

// ImageableTypeContainsFold applies the ContainsFold predicate on the "imageable_type" field.
func ImageableTypeContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldImageableType, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldURL, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldWidth, v))
}

// WidthIsNil applies the IsNil predicate on the "width" field.
func WidthIsNil() predicate.Image {
	return predicate.Image(sql.FieldIsNull(FieldWidth))
}

// WidthNotNil applies the NotNil predicate on the "width" field.
func WidthNotNil() predicate.Image {
	return predicate.Image(sql.FieldNotNull(FieldWidth))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.Image {
	return predicate.Image(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.Image {
	return predicate.Image(sql.FieldNotNull(FieldHeight))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Image) predicate.Image {
	return predicate.Image(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Image) predicate.Image {
	return predicate.Image(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Image) predicate.Image {
	return predicate.Image(sql.NotPredicates(p))
}
