// Code generated by ent, DO NOT EDIT.

package annotation

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the annotation type in the database.
	Label = "annotation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTargetID holds the string denoting the target_id field in the database.
	FieldTargetID = "target_id"
	// FieldTargetType holds the string denoting the target_type field in the database.
	FieldTargetType = "target_type"
	// FieldSecondaryID holds the string denoting the secondary_id field in the database.
	FieldSecondaryID = "secondary_id"
	// FieldSecondaryType holds the string denoting the secondary_type field in the database.
	FieldSecondaryType = "secondary_type"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// Table holds the table name of the annotation in the database.
	Table = "annotations"
)

// Columns holds all SQL columns for annotation fields.
var Columns = []string{
	FieldID,
	FieldTargetID,
	FieldTargetType,
	FieldSecondaryID,
	FieldSecondaryType,
	FieldBody,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// TargetType defines the type for the "target_type" enum field.
type TargetType string

// TargetType values.
const (
	TargetTypeDocument TargetType = "document"
	TargetTypeReport   TargetType = "report"
)

func (tt TargetType) String() string {
	return string(tt)
}

// TargetTypeValidator is a validator for the "target_type" field enum values. It is called by the builders before save.
func TargetTypeValidator(tt TargetType) error {
	switch tt {
	case TargetTypeDocument, TargetTypeReport:
		return nil
	default:
		return fmt.Errorf("annotation: invalid enum value for target_type field: %q", tt)
	}
}

// SecondaryType defines the type for the "secondary_type" enum field.
type SecondaryType string

// SecondaryType values.
const (
	SecondaryTypePost  SecondaryType = "post"
	SecondaryTypeVideo SecondaryType = "video"
)

func (st SecondaryType) String() string {
	return string(st)
}

// SecondaryTypeValidator is a validator for the "secondary_type" field enum values. It is called by the builders before save.
func SecondaryTypeValidator(st SecondaryType) error {
	switch st {
	case SecondaryTypePost, SecondaryTypeVideo:
		return nil
	default:
		return fmt.Errorf("annotation: invalid enum value for secondary_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the Annotation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTargetID orders the results by the target_id field.
func ByTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetID, opts...).ToFunc()
}

// ByTargetType orders the results by the target_type field.
func ByTargetType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetType, opts...).ToFunc()
}

// BySecondaryID orders the results by the secondary_id field.
func BySecondaryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecondaryID, opts...).ToFunc()
}

// BySecondaryType orders the results by the secondary_type field.
func BySecondaryType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecondaryType, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}
