// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Post) Author(ctx context.Context) (*User, error) {
	result, err := _m.Edges.AuthorOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAuthor().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Post) Tags(ctx context.Context) (result []*Tag, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedTags(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.TagsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryTags().All(ctx)
	}
	return result, err
}

func (_m *Tag) Posts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPosts().All(ctx)
	}
	return result, err
}

func (_m *User) Posts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPosts().All(ctx)
	}
	return result, err
}
