// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Annotation is the predicate function for annotation builders.
type Annotation func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// Report is the predicate function for report builders.
type Report func(*sql.Selector)
