package apipub

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/khanakia/entx/testentgqlmulti/ent"
)

// PublicChatbots is the resolver for the publicChatbots field.
func (r *queryResolver) PublicChatbots(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int) (*PublicChatbotConnection, error) {
	conn, err := r.Client.Chatbot.Query().Paginate(ctx, after, first, before, last)
	if err != nil {
		return nil, err
	}
	out := &PublicChatbotConnection{
		PageInfo:   &conn.PageInfo,
		TotalCount: conn.TotalCount,
	}
	for _, e := range conn.Edges {
		out.Edges = append(out.Edges, &PublicChatbotEdge{Node: e.Node, Cursor: e.Cursor})
	}
	return out, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int) (*ent.TagConnection, error) {
	return r.Client.Tag.Query().Paginate(ctx, after, first, before, last)
}

// PublicUsers is the resolver for the publicUsers field.
func (r *queryResolver) PublicUsers(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.UserWhereInput) (*PublicUserConnection, error) {
	opts := []ent.UserPaginateOption{ent.WithUserFilter(where.Filter)}
	conn, err := r.Client.User.Query().Paginate(ctx, after, first, before, last, opts...)
	if err != nil {
		return nil, err
	}
	out := &PublicUserConnection{
		PageInfo:   &conn.PageInfo,
		TotalCount: conn.TotalCount,
	}
	for _, e := range conn.Edges {
		out.Edges = append(out.Edges, &PublicUserEdge{Node: e.Node, Cursor: e.Cursor})
	}
	return out, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
