// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package apidash

import (
	"entgo.io/contrib/entgql"
	"github.com/khanakia/entx/testentgqlmulti/ent"
)

// A connection to a list of items.
type ChatbotSummaryConnection struct {
	// A list of edges.
	Edges []*ChatbotSummaryEdge `json:"edges,omitempty"`
	// Information to aid in pagination.
	PageInfo *entgql.PageInfo[int] `json:"pageInfo"`
	// Identifies the total count of items in the connection.
	TotalCount int `json:"totalCount"`
}

// An edge in a connection.
type ChatbotSummaryEdge struct {
	// The item at the end of the edge.
	Node *ent.Chatbot `json:"node,omitempty"`
	// A cursor for use in pagination.
	Cursor entgql.Cursor[int] `json:"cursor"`
}
