package testentgqlmulti

import (
	"testing"
)

// ---------------------------------------------------------------------------
// Dashboard API (apidash) — full CRUD, where, orderBy, multi-target.
// ---------------------------------------------------------------------------

// TestApidash_CreateAndQueryUser covers the golden path for a full CRUD API:
// a createUser mutation returns a full User node, and a subsequent users
// connection query paginates over it.
func TestApidash_CreateAndQueryUser(t *testing.T) {
	f := NewFixture(t)

	var createResp struct {
		CreateUser struct {
			ID        int    `json:"id"`
			FirstName string `json:"firstName"`
			Status    string `json:"status"`
		} `json:"createUser"`
	}
	doGQL(t, f.Dash.URL, `
		mutation ($in: CreateUserInput!) {
			createUser(input: $in) { id firstName status }
		}
	`, map[string]any{"in": map[string]any{
		"firstName": "Ada",
		"lastName":  "Lovelace",
		"email":     "ada@example.com",
	}}, &createResp)

	if createResp.CreateUser.FirstName != "Ada" {
		t.Fatalf("createUser.firstName = %q, want Ada", createResp.CreateUser.FirstName)
	}
	if createResp.CreateUser.Status != "active" {
		t.Fatalf("createUser.status default mismatch: %q", createResp.CreateUser.Status)
	}

	var listResp struct {
		Users struct {
			TotalCount int `json:"totalCount"`
			Edges      []struct {
				Node struct{ FirstName string `json:"firstName"` } `json:"node"`
			} `json:"edges"`
		} `json:"users"`
	}
	doGQL(t, f.Dash.URL, `
		{ users { totalCount edges { node { firstName } } } }
	`, nil, &listResp)
	if listResp.Users.TotalCount != 1 {
		t.Fatalf("users.totalCount = %d, want 1", listResp.Users.TotalCount)
	}
	if listResp.Users.Edges[0].Node.FirstName != "Ada" {
		t.Fatalf("listed user firstName mismatch: %+v", listResp.Users.Edges)
	}
}

// TestApidash_OrderByAndWhere exercises the OrderBy+Filters args generated by
// the WithOrderBy/WithFilters targets. We insert two users and verify the
// filter narrows the result and the order argument flips the sequence.
func TestApidash_OrderByAndWhere(t *testing.T) {
	f := NewFixture(t)

	for _, name := range []string{"Ada", "Ben"} {
		doGQL(t, f.Dash.URL, `
			mutation ($in: CreateUserInput!) {
				createUser(input: $in) { id }
			}
		`, map[string]any{"in": map[string]any{
			"firstName": name,
			"lastName":  "X",
			"email":     name + "@example.com",
		}}, nil)
	}

	// Filter: firstName = "Ada"
	var filteredResp struct {
		Users struct {
			Edges []struct{ Node struct{ FirstName string `json:"firstName"` } `json:"node"` } `json:"edges"`
		} `json:"users"`
	}
	doGQL(t, f.Dash.URL, `
		query ($w: UserWhereInput) {
			users(where: $w) { edges { node { firstName } } }
		}
	`, map[string]any{"w": map[string]any{"firstName": "Ada"}}, &filteredResp)
	if len(filteredResp.Users.Edges) != 1 || filteredResp.Users.Edges[0].Node.FirstName != "Ada" {
		t.Fatalf("where firstName=Ada: %+v", filteredResp.Users.Edges)
	}

	// Order: FIRST_NAME DESC -> Ben before Ada
	var orderedResp struct {
		Users struct {
			Edges []struct{ Node struct{ FirstName string `json:"firstName"` } `json:"node"` } `json:"edges"`
		} `json:"users"`
	}
	doGQL(t, f.Dash.URL, `
		query {
			users(orderBy: [{direction: DESC, field: FIRST_NAME}]) {
				edges { node { firstName } }
			}
		}
	`, nil, &orderedResp)
	got := []string{
		orderedResp.Users.Edges[0].Node.FirstName,
		orderedResp.Users.Edges[1].Node.FirstName,
	}
	if got[0] != "Ben" || got[1] != "Ada" {
		t.Fatalf("orderBy FIRST_NAME DESC = %v, want [Ben Ada]", got)
	}
}

// TestApidash_MultiTargetPerEntity proves two subset types (Chatbot and
// ChatbotSummary) backed by the same ent struct coexist in one schema and
// resolve correctly through distinct query fields.
func TestApidash_MultiTargetPerEntity(t *testing.T) {
	f := NewFixture(t)

	doGQL(t, f.Dash.URL, `
		mutation ($in: CreateChatbotInput!) {
			createChatbot(input: $in) { id name status }
		}
	`, map[string]any{"in": map[string]any{
		"name":   "Sparkles",
		"apiKey": "secret-key",
	}}, nil)

	// Full Chatbot query surfaces all fields.
	var fullResp struct {
		Chatbots struct {
			Edges []struct {
				Node struct {
					Name        string  `json:"name"`
					Avatar      *string `json:"avatar"`
					Description *string `json:"description"`
					Status      string  `json:"status"`
				} `json:"node"`
			} `json:"edges"`
		} `json:"chatbots"`
	}
	doGQL(t, f.Dash.URL, `
		{ chatbots { edges { node { name avatar description status } } } }
	`, nil, &fullResp)
	if len(fullResp.Chatbots.Edges) != 1 || fullResp.Chatbots.Edges[0].Node.Name != "Sparkles" {
		t.Fatalf("chatbots edges: %+v", fullResp.Chatbots.Edges)
	}

	// Summary query surfaces only id+name+status.
	var sumResp struct {
		ChatbotSummaries struct {
			Edges []struct {
				Node struct {
					Name   string `json:"name"`
					Status string `json:"status"`
				} `json:"node"`
			} `json:"edges"`
		} `json:"chatbotSummaries"`
	}
	doGQL(t, f.Dash.URL, `
		{ chatbotSummaries { edges { node { name status } } } }
	`, nil, &sumResp)
	if len(sumResp.ChatbotSummaries.Edges) != 1 || sumResp.ChatbotSummaries.Edges[0].Node.Name != "Sparkles" {
		t.Fatalf("chatbotSummaries edges: %+v", sumResp.ChatbotSummaries.Edges)
	}

	// ChatbotSummary must NOT expose api_key/avatar/description.
	errResp := doGQLExpectError(t, f.Dash.URL, `
		{ chatbotSummaries { edges { node { apiKey } } } }
	`, nil)
	if errResp.Errors[0].Message == "" {
		t.Fatalf("expected 'Cannot query field' error, got %+v", errResp.Errors)
	}
}

// TestApidash_NodeInterfaceOnFullTypes verifies that the main Chatbot type
// still has the auto-generated Node machinery (even though entgqlmulti strips
// the interface from subset types). We check this indirectly by resolving
// Chatbot via its plain query.
func TestApidash_UpdateMutation(t *testing.T) {
	f := NewFixture(t)

	var created struct {
		CreateChatbot struct {
			ID int `json:"id"`
		} `json:"createChatbot"`
	}
	doGQL(t, f.Dash.URL, `
		mutation ($in: CreateChatbotInput!) {
			createChatbot(input: $in) { id }
		}
	`, map[string]any{"in": map[string]any{
		"name":   "Before",
		"apiKey": "k",
	}}, &created)

	var updated struct {
		UpdateChatbot struct {
			Name string `json:"name"`
		} `json:"updateChatbot"`
	}
	doGQL(t, f.Dash.URL, `
		mutation ($id: ID!, $in: UpdateChatbotInput!) {
			updateChatbot(id: $id, input: $in) { name }
		}
	`, map[string]any{
		"id": created.CreateChatbot.ID,
		"in": map[string]any{"name": "After"},
	}, &updated)

	if updated.UpdateChatbot.Name != "After" {
		t.Fatalf("updateChatbot.name = %q", updated.UpdateChatbot.Name)
	}
}
