// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/entx/entpoly/examples/morphstring/ent/comment"
	"github.com/khanakia/entx/entpoly/examples/morphstring/ent/predicate"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks     []Hook
	mutation  *CommentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCommentableID sets the "commentable_id" field.
func (_u *CommentUpdate) SetCommentableID(v string) *CommentUpdate {
	_u.mutation.SetCommentableID(v)
	return _u
}

// SetNillableCommentableID sets the "commentable_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableCommentableID(v *string) *CommentUpdate {
	if v != nil {
		_u.SetCommentableID(*v)
	}
	return _u
}

// ClearCommentableID clears the value of the "commentable_id" field.
func (_u *CommentUpdate) ClearCommentableID() *CommentUpdate {
	_u.mutation.ClearCommentableID()
	return _u
}

// SetCommentableType sets the "commentable_type" field.
func (_u *CommentUpdate) SetCommentableType(v string) *CommentUpdate {
	_u.mutation.SetCommentableType(v)
	return _u
}

// SetNillableCommentableType sets the "commentable_type" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableCommentableType(v *string) *CommentUpdate {
	if v != nil {
		_u.SetCommentableType(*v)
	}
	return _u
}

// ClearCommentableType clears the value of the "commentable_type" field.
func (_u *CommentUpdate) ClearCommentableType() *CommentUpdate {
	_u.mutation.ClearCommentableType()
	return _u
}

// SetBody sets the "body" field.
func (_u *CommentUpdate) SetBody(v string) *CommentUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableBody(v *string) *CommentUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdate) Mutation() *CommentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CommentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CommentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CommentableID(); ok {
		_spec.SetField(comment.FieldCommentableID, field.TypeString, value)
	}
	if _u.mutation.CommentableIDCleared() {
		_spec.ClearField(comment.FieldCommentableID, field.TypeString)
	}
	if value, ok := _u.mutation.CommentableType(); ok {
		_spec.SetField(comment.FieldCommentableType, field.TypeString, value)
	}
	if _u.mutation.CommentableTypeCleared() {
		_spec.ClearField(comment.FieldCommentableType, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(comment.FieldBody, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CommentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCommentableID sets the "commentable_id" field.
func (_u *CommentUpdateOne) SetCommentableID(v string) *CommentUpdateOne {
	_u.mutation.SetCommentableID(v)
	return _u
}

// SetNillableCommentableID sets the "commentable_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableCommentableID(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetCommentableID(*v)
	}
	return _u
}

// ClearCommentableID clears the value of the "commentable_id" field.
func (_u *CommentUpdateOne) ClearCommentableID() *CommentUpdateOne {
	_u.mutation.ClearCommentableID()
	return _u
}

// SetCommentableType sets the "commentable_type" field.
func (_u *CommentUpdateOne) SetCommentableType(v string) *CommentUpdateOne {
	_u.mutation.SetCommentableType(v)
	return _u
}

// SetNillableCommentableType sets the "commentable_type" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableCommentableType(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetCommentableType(*v)
	}
	return _u
}

// ClearCommentableType clears the value of the "commentable_type" field.
func (_u *CommentUpdateOne) ClearCommentableType() *CommentUpdateOne {
	_u.mutation.ClearCommentableType()
	return _u
}

// SetBody sets the "body" field.
func (_u *CommentUpdateOne) SetBody(v string) *CommentUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableBody(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdateOne) Mutation() *CommentMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Comment entity.
func (_u *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CommentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CommentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CommentableID(); ok {
		_spec.SetField(comment.FieldCommentableID, field.TypeString, value)
	}
	if _u.mutation.CommentableIDCleared() {
		_spec.ClearField(comment.FieldCommentableID, field.TypeString)
	}
	if value, ok := _u.mutation.CommentableType(); ok {
		_spec.SetField(comment.FieldCommentableType, field.TypeString, value)
	}
	if _u.mutation.CommentableTypeCleared() {
		_spec.ClearField(comment.FieldCommentableType, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(comment.FieldBody, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Comment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
