// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/entx/entpoly/examples/morphstring/ent/sourcelink"
)

// SourceLinkCreate is the builder for creating a SourceLink entity.
type SourceLinkCreate struct {
	config
	mutation *SourceLinkMutation
	hooks    []Hook
}

// SetSourceableID sets the "sourceable_id" field.
func (_c *SourceLinkCreate) SetSourceableID(v string) *SourceLinkCreate {
	_c.mutation.SetSourceableID(v)
	return _c
}

// SetNillableSourceableID sets the "sourceable_id" field if the given value is not nil.
func (_c *SourceLinkCreate) SetNillableSourceableID(v *string) *SourceLinkCreate {
	if v != nil {
		_c.SetSourceableID(*v)
	}
	return _c
}

// SetSourceableType sets the "sourceable_type" field.
func (_c *SourceLinkCreate) SetSourceableType(v string) *SourceLinkCreate {
	_c.mutation.SetSourceableType(v)
	return _c
}

// SetNillableSourceableType sets the "sourceable_type" field if the given value is not nil.
func (_c *SourceLinkCreate) SetNillableSourceableType(v *string) *SourceLinkCreate {
	if v != nil {
		_c.SetSourceableType(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *SourceLinkCreate) SetURL(v string) *SourceLinkCreate {
	_c.mutation.SetURL(v)
	return _c
}

// Mutation returns the SourceLinkMutation object of the builder.
func (_c *SourceLinkCreate) Mutation() *SourceLinkMutation {
	return _c.mutation
}

// Save creates the SourceLink in the database.
func (_c *SourceLinkCreate) Save(ctx context.Context) (*SourceLink, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SourceLinkCreate) SaveX(ctx context.Context) *SourceLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SourceLinkCreate) check() error {
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "SourceLink.url"`)}
	}
	return nil
}

func (_c *SourceLinkCreate) sqlSave(ctx context.Context) (*SourceLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SourceLinkCreate) createSpec() (*SourceLink, *sqlgraph.CreateSpec) {
	var (
		_node = &SourceLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sourcelink.Table, sqlgraph.NewFieldSpec(sourcelink.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SourceableID(); ok {
		_spec.SetField(sourcelink.FieldSourceableID, field.TypeString, value)
		_node.SourceableID = &value
	}
	if value, ok := _c.mutation.SourceableType(); ok {
		_spec.SetField(sourcelink.FieldSourceableType, field.TypeString, value)
		_node.SourceableType = &value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(sourcelink.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	return _node, _spec
}

// SourceLinkCreateBulk is the builder for creating many SourceLink entities in bulk.
type SourceLinkCreateBulk struct {
	config
	err      error
	builders []*SourceLinkCreate
}

// Save creates the SourceLink entities in the database.
func (_c *SourceLinkCreateBulk) Save(ctx context.Context) ([]*SourceLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SourceLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SourceLinkCreateBulk) SaveX(ctx context.Context) []*SourceLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
