// Code generated by ent, DO NOT EDIT.

package bookmark

import (
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/entx/entpoly/examples/morphstring/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldID, id))
}

// PinnableID applies equality check predicate on the "pinnable_id" field. It's identical to PinnableIDEQ.
func PinnableID(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldPinnableID, v))
}

// PinnableType applies equality check predicate on the "pinnable_type" field. It's identical to PinnableTypeEQ.
func PinnableType(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldPinnableType, v))
}

// PinnableIDEQ applies the EQ predicate on the "pinnable_id" field.
func PinnableIDEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldPinnableID, v))
}

// PinnableIDNEQ applies the NEQ predicate on the "pinnable_id" field.
func PinnableIDNEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldPinnableID, v))
}

// PinnableIDIn applies the In predicate on the "pinnable_id" field.
func PinnableIDIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldPinnableID, vs...))
}

// PinnableIDNotIn applies the NotIn predicate on the "pinnable_id" field.
func PinnableIDNotIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldPinnableID, vs...))
}

// PinnableIDGT applies the GT predicate on the "pinnable_id" field.
func PinnableIDGT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldPinnableID, v))
}

// PinnableIDGTE applies the GTE predicate on the "pinnable_id" field.
func PinnableIDGTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldPinnableID, v))
}

// PinnableIDLT applies the LT predicate on the "pinnable_id" field.
func PinnableIDLT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldPinnableID, v))
}

// PinnableIDLTE applies the LTE predicate on the "pinnable_id" field.
func PinnableIDLTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldPinnableID, v))
}

// PinnableIDContains applies the Contains predicate on the "pinnable_id" field.
func PinnableIDContains(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContains(FieldPinnableID, v))
}

// PinnableIDHasPrefix applies the HasPrefix predicate on the "pinnable_id" field.
func PinnableIDHasPrefix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasPrefix(FieldPinnableID, v))
}

// PinnableIDHasSuffix applies the HasSuffix predicate on the "pinnable_id" field.
func PinnableIDHasSuffix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasSuffix(FieldPinnableID, v))
}

// PinnableIDIsNil applies the IsNil predicate on the "pinnable_id" field.
func PinnableIDIsNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIsNull(FieldPinnableID))
}

// PinnableIDNotNil applies the NotNil predicate on the "pinnable_id" field.
func PinnableIDNotNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotNull(FieldPinnableID))
}

// PinnableIDEqualFold applies the EqualFold predicate on the "pinnable_id" field.
func PinnableIDEqualFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEqualFold(FieldPinnableID, v))
}

// PinnableIDContainsFold applies the ContainsFold predicate on the "pinnable_id" field.
func PinnableIDContainsFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContainsFold(FieldPinnableID, v))
}

// PinnableTypeEQ applies the EQ predicate on the "pinnable_type" field.
func PinnableTypeEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldPinnableType, v))
}

// PinnableTypeNEQ applies the NEQ predicate on the "pinnable_type" field.
func PinnableTypeNEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldPinnableType, v))
}

// PinnableTypeIn applies the In predicate on the "pinnable_type" field.
func PinnableTypeIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldPinnableType, vs...))
}

// PinnableTypeNotIn applies the NotIn predicate on the "pinnable_type" field.
func PinnableTypeNotIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldPinnableType, vs...))
}

// PinnableTypeGT applies the GT predicate on the "pinnable_type" field.
func PinnableTypeGT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldPinnableType, v))
}

// PinnableTypeGTE applies the GTE predicate on the "pinnable_type" field.
func PinnableTypeGTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldPinnableType, v))
}

// PinnableTypeLT applies the LT predicate on the "pinnable_type" field.
func PinnableTypeLT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldPinnableType, v))
}

// PinnableTypeLTE applies the LTE predicate on the "pinnable_type" field.
func PinnableTypeLTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldPinnableType, v))
}

// PinnableTypeContains applies the Contains predicate on the "pinnable_type" field.
func PinnableTypeContains(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContains(FieldPinnableType, v))
}

// PinnableTypeHasPrefix applies the HasPrefix predicate on the "pinnable_type" field.
func PinnableTypeHasPrefix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasPrefix(FieldPinnableType, v))
}

// PinnableTypeHasSuffix applies the HasSuffix predicate on the "pinnable_type" field.
func PinnableTypeHasSuffix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasSuffix(FieldPinnableType, v))
}

// PinnableTypeIsNil applies the IsNil predicate on the "pinnable_type" field.
func PinnableTypeIsNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIsNull(FieldPinnableType))
}

// PinnableTypeNotNil applies the NotNil predicate on the "pinnable_type" field.
func PinnableTypeNotNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotNull(FieldPinnableType))
}

// PinnableTypeEqualFold applies the EqualFold predicate on the "pinnable_type" field.
func PinnableTypeEqualFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEqualFold(FieldPinnableType, v))
}

// PinnableTypeContainsFold applies the ContainsFold predicate on the "pinnable_type" field.
func PinnableTypeContainsFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContainsFold(FieldPinnableType, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContainsFold(FieldLabel, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bookmark) predicate.Bookmark {
	return predicate.Bookmark(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bookmark) predicate.Bookmark {
	return predicate.Bookmark(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bookmark) predicate.Bookmark {
	return predicate.Bookmark(sql.NotPredicates(p))
}
