// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PostTag is the predicate function for posttag builders.
type PostTag func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Revision is the predicate function for revision builders.
type Revision func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
