// Code generated by ent, DO NOT EDIT.

package comment

import (
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/entx/entpoly/examples/morphstring/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldID, id))
}

// CommentableID applies equality check predicate on the "commentable_id" field. It's identical to CommentableIDEQ.
func CommentableID(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldCommentableID, v))
}

// CommentableType applies equality check predicate on the "commentable_type" field. It's identical to CommentableTypeEQ.
func CommentableType(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldCommentableType, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldBody, v))
}

// CommentableIDEQ applies the EQ predicate on the "commentable_id" field.
func CommentableIDEQ(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldCommentableID, v))
}

// CommentableIDNEQ applies the NEQ predicate on the "commentable_id" field.
func CommentableIDNEQ(v string) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldCommentableID, v))
}

// CommentableIDIn applies the In predicate on the "commentable_id" field.
func CommentableIDIn(vs ...string) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldCommentableID, vs...))
}

// CommentableIDNotIn applies the NotIn predicate on the "commentable_id" field.
func CommentableIDNotIn(vs ...string) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldCommentableID, vs...))
}

// CommentableIDGT applies the GT predicate on the "commentable_id" field.
func CommentableIDGT(v string) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldCommentableID, v))
}

// CommentableIDGTE applies the GTE predicate on the "commentable_id" field.
func CommentableIDGTE(v string) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldCommentableID, v))
}

// CommentableIDLT applies the LT predicate on the "commentable_id" field.
func CommentableIDLT(v string) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldCommentableID, v))
}

// CommentableIDLTE applies the LTE predicate on the "commentable_id" field.
func CommentableIDLTE(v string) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldCommentableID, v))
}

// CommentableIDContains applies the Contains predicate on the "commentable_id" field.
func CommentableIDContains(v string) predicate.Comment {
	return predicate.Comment(sql.FieldContains(FieldCommentableID, v))
}

// CommentableIDHasPrefix applies the HasPrefix predicate on the "commentable_id" field.
func CommentableIDHasPrefix(v string) predicate.Comment {
	return predicate.Comment(sql.FieldHasPrefix(FieldCommentableID, v))
}

// CommentableIDHasSuffix applies the HasSuffix predicate on the "commentable_id" field.
func CommentableIDHasSuffix(v string) predicate.Comment {
	return predicate.Comment(sql.FieldHasSuffix(FieldCommentableID, v))
}

// CommentableIDIsNil applies the IsNil predicate on the "commentable_id" field.
func CommentableIDIsNil() predicate.Comment {
	return predicate.Comment(sql.FieldIsNull(FieldCommentableID))
}

// CommentableIDNotNil applies the NotNil predicate on the "commentable_id" field.
func CommentableIDNotNil() predicate.Comment {
	return predicate.Comment(sql.FieldNotNull(FieldCommentableID))
}

// CommentableIDEqualFold applies the EqualFold predicate on the "commentable_id" field.
func CommentableIDEqualFold(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEqualFold(FieldCommentableID, v))
}

// CommentableIDContainsFold applies the ContainsFold predicate on the "commentable_id" field.
func CommentableIDContainsFold(v string) predicate.Comment {
	return predicate.Comment(sql.FieldContainsFold(FieldCommentableID, v))
}

// CommentableTypeEQ applies the EQ predicate on the "commentable_type" field.
func CommentableTypeEQ(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldCommentableType, v))
}

// CommentableTypeNEQ applies the NEQ predicate on the "commentable_type" field.
func CommentableTypeNEQ(v string) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldCommentableType, v))
}

// CommentableTypeIn applies the In predicate on the "commentable_type" field.
func CommentableTypeIn(vs ...string) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldCommentableType, vs...))
}

// CommentableTypeNotIn applies the NotIn predicate on the "commentable_type" field.
func CommentableTypeNotIn(vs ...string) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldCommentableType, vs...))
}

// CommentableTypeGT applies the GT predicate on the "commentable_type" field.
func CommentableTypeGT(v string) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldCommentableType, v))
}

// CommentableTypeGTE applies the GTE predicate on the "commentable_type" field.
func CommentableTypeGTE(v string) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldCommentableType, v))
}

// CommentableTypeLT applies the LT predicate on the "commentable_type" field.
func CommentableTypeLT(v string) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldCommentableType, v))
}

// CommentableTypeLTE applies the LTE predicate on the "commentable_type" field.
func CommentableTypeLTE(v string) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldCommentableType, v))
}

// CommentableTypeContains applies the Contains predicate on the "commentable_type" field.
func CommentableTypeContains(v string) predicate.Comment {
	return predicate.Comment(sql.FieldContains(FieldCommentableType, v))
}

// CommentableTypeHasPrefix applies the HasPrefix predicate on the "commentable_type" field.
func CommentableTypeHasPrefix(v string) predicate.Comment {
	return predicate.Comment(sql.FieldHasPrefix(FieldCommentableType, v))
}

// CommentableTypeHasSuffix applies the HasSuffix predicate on the "commentable_type" field.
func CommentableTypeHasSuffix(v string) predicate.Comment {
	return predicate.Comment(sql.FieldHasSuffix(FieldCommentableType, v))
}

// CommentableTypeIsNil applies the IsNil predicate on the "commentable_type" field.
func CommentableTypeIsNil() predicate.Comment {
	return predicate.Comment(sql.FieldIsNull(FieldCommentableType))
}

// CommentableTypeNotNil applies the NotNil predicate on the "commentable_type" field.
func CommentableTypeNotNil() predicate.Comment {
	return predicate.Comment(sql.FieldNotNull(FieldCommentableType))
}

// CommentableTypeEqualFold applies the EqualFold predicate on the "commentable_type" field.
func CommentableTypeEqualFold(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEqualFold(FieldCommentableType, v))
}

// CommentableTypeContainsFold applies the ContainsFold predicate on the "commentable_type" field.
func CommentableTypeContainsFold(v string) predicate.Comment {
	return predicate.Comment(sql.FieldContainsFold(FieldCommentableType, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.Comment {
	return predicate.Comment(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.Comment {
	return predicate.Comment(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.Comment {
	return predicate.Comment(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.Comment {
	return predicate.Comment(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.Comment {
	return predicate.Comment(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.Comment {
	return predicate.Comment(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.Comment {
	return predicate.Comment(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.Comment {
	return predicate.Comment(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.Comment {
	return predicate.Comment(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.Comment {
	return predicate.Comment(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.Comment {
	return predicate.Comment(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.Comment {
	return predicate.Comment(sql.FieldContainsFold(FieldBody, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Comment) predicate.Comment {
	return predicate.Comment(sql.NotPredicates(p))
}
