// Code generated by ent, DO NOT EDIT.

package taggable

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the taggable type in the database.
	Label = "taggable"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaggableID holds the string denoting the taggable_id field in the database.
	FieldTaggableID = "taggable_id"
	// FieldTaggableType holds the string denoting the taggable_type field in the database.
	FieldTaggableType = "taggable_type"
	// FieldTagID holds the string denoting the tag_id field in the database.
	FieldTagID = "tag_id"
	// FieldAddedBy holds the string denoting the added_by field in the database.
	FieldAddedBy = "added_by"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// Table holds the table name of the taggable in the database.
	Table = "taggables"
)

// Columns holds all SQL columns for taggable fields.
var Columns = []string{
	FieldID,
	FieldTaggableID,
	FieldTaggableType,
	FieldTagID,
	FieldAddedBy,
	FieldSortOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the Taggable queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaggableID orders the results by the taggable_id field.
func ByTaggableID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaggableID, opts...).ToFunc()
}

// ByTaggableType orders the results by the taggable_type field.
func ByTaggableType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaggableType, opts...).ToFunc()
}

// ByTagID orders the results by the tag_id field.
func ByTagID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTagID, opts...).ToFunc()
}

// ByAddedBy orders the results by the added_by field.
func ByAddedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddedBy, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}
