// Code generated by ent, DO NOT EDIT.

package taggable

import (
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/entx/entpoly/examples/basic/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Taggable {
	return predicate.Taggable(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Taggable {
	return predicate.Taggable(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Taggable {
	return predicate.Taggable(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Taggable {
	return predicate.Taggable(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Taggable {
	return predicate.Taggable(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Taggable {
	return predicate.Taggable(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Taggable {
	return predicate.Taggable(sql.FieldLTE(FieldID, id))
}

// TaggableID applies equality check predicate on the "taggable_id" field. It's identical to TaggableIDEQ.
func TaggableID(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldTaggableID, v))
}

// TaggableType applies equality check predicate on the "taggable_type" field. It's identical to TaggableTypeEQ.
func TaggableType(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldTaggableType, v))
}

// TagID applies equality check predicate on the "tag_id" field. It's identical to TagIDEQ.
func TagID(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldTagID, v))
}

// AddedBy applies equality check predicate on the "added_by" field. It's identical to AddedByEQ.
func AddedBy(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldAddedBy, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldSortOrder, v))
}

// TaggableIDEQ applies the EQ predicate on the "taggable_id" field.
func TaggableIDEQ(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldTaggableID, v))
}

// TaggableIDNEQ applies the NEQ predicate on the "taggable_id" field.
func TaggableIDNEQ(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldNEQ(FieldTaggableID, v))
}

// TaggableIDIn applies the In predicate on the "taggable_id" field.
func TaggableIDIn(vs ...string) predicate.Taggable {
	return predicate.Taggable(sql.FieldIn(FieldTaggableID, vs...))
}

// TaggableIDNotIn applies the NotIn predicate on the "taggable_id" field.
func TaggableIDNotIn(vs ...string) predicate.Taggable {
	return predicate.Taggable(sql.FieldNotIn(FieldTaggableID, vs...))
}

// TaggableIDGT applies the GT predicate on the "taggable_id" field.
func TaggableIDGT(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldGT(FieldTaggableID, v))
}

// TaggableIDGTE applies the GTE predicate on the "taggable_id" field.
func TaggableIDGTE(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldGTE(FieldTaggableID, v))
}

// TaggableIDLT applies the LT predicate on the "taggable_id" field.
func TaggableIDLT(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldLT(FieldTaggableID, v))
}

// TaggableIDLTE applies the LTE predicate on the "taggable_id" field.
func TaggableIDLTE(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldLTE(FieldTaggableID, v))
}

// TaggableIDContains applies the Contains predicate on the "taggable_id" field.
func TaggableIDContains(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldContains(FieldTaggableID, v))
}

// TaggableIDHasPrefix applies the HasPrefix predicate on the "taggable_id" field.
func TaggableIDHasPrefix(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldHasPrefix(FieldTaggableID, v))
}

// TaggableIDHasSuffix applies the HasSuffix predicate on the "taggable_id" field.
func TaggableIDHasSuffix(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldHasSuffix(FieldTaggableID, v))
}

// TaggableIDIsNil applies the IsNil predicate on the "taggable_id" field.
func TaggableIDIsNil() predicate.Taggable {
	return predicate.Taggable(sql.FieldIsNull(FieldTaggableID))
}

// TaggableIDNotNil applies the NotNil predicate on the "taggable_id" field.
func TaggableIDNotNil() predicate.Taggable {
	return predicate.Taggable(sql.FieldNotNull(FieldTaggableID))
}

// TaggableIDEqualFold applies the EqualFold predicate on the "taggable_id" field.
func TaggableIDEqualFold(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEqualFold(FieldTaggableID, v))
}

// TaggableIDContainsFold applies the ContainsFold predicate on the "taggable_id" field.
func TaggableIDContainsFold(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldContainsFold(FieldTaggableID, v))
}

// TaggableTypeEQ applies the EQ predicate on the "taggable_type" field.
func TaggableTypeEQ(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldTaggableType, v))
}

// TaggableTypeNEQ applies the NEQ predicate on the "taggable_type" field.
func TaggableTypeNEQ(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldNEQ(FieldTaggableType, v))
}

// TaggableTypeIn applies the In predicate on the "taggable_type" field.
func TaggableTypeIn(vs ...string) predicate.Taggable {
	return predicate.Taggable(sql.FieldIn(FieldTaggableType, vs...))
}

// TaggableTypeNotIn applies the NotIn predicate on the "taggable_type" field.
func TaggableTypeNotIn(vs ...string) predicate.Taggable {
	return predicate.Taggable(sql.FieldNotIn(FieldTaggableType, vs...))
}

// TaggableTypeGT applies the GT predicate on the "taggable_type" field.
func TaggableTypeGT(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldGT(FieldTaggableType, v))
}

// TaggableTypeGTE applies the GTE predicate on the "taggable_type" field.
func TaggableTypeGTE(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldGTE(FieldTaggableType, v))
}

// TaggableTypeLT applies the LT predicate on the "taggable_type" field.
func TaggableTypeLT(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldLT(FieldTaggableType, v))
}

// TaggableTypeLTE applies the LTE predicate on the "taggable_type" field.
func TaggableTypeLTE(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldLTE(FieldTaggableType, v))
}

// TaggableTypeContains applies the Contains predicate on the "taggable_type" field.
func TaggableTypeContains(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldContains(FieldTaggableType, v))
}

// TaggableTypeHasPrefix applies the HasPrefix predicate on the "taggable_type" field.
func TaggableTypeHasPrefix(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldHasPrefix(FieldTaggableType, v))
}

// TaggableTypeHasSuffix applies the HasSuffix predicate on the "taggable_type" field.
func TaggableTypeHasSuffix(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldHasSuffix(FieldTaggableType, v))
}

// TaggableTypeIsNil applies the IsNil predicate on the "taggable_type" field.
func TaggableTypeIsNil() predicate.Taggable {
	return predicate.Taggable(sql.FieldIsNull(FieldTaggableType))
}

// TaggableTypeNotNil applies the NotNil predicate on the "taggable_type" field.
func TaggableTypeNotNil() predicate.Taggable {
	return predicate.Taggable(sql.FieldNotNull(FieldTaggableType))
}

// TaggableTypeEqualFold applies the EqualFold predicate on the "taggable_type" field.
func TaggableTypeEqualFold(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEqualFold(FieldTaggableType, v))
}

// TaggableTypeContainsFold applies the ContainsFold predicate on the "taggable_type" field.
func TaggableTypeContainsFold(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldContainsFold(FieldTaggableType, v))
}

// TagIDEQ applies the EQ predicate on the "tag_id" field.
func TagIDEQ(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldTagID, v))
}

// TagIDNEQ applies the NEQ predicate on the "tag_id" field.
func TagIDNEQ(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldNEQ(FieldTagID, v))
}

// TagIDIn applies the In predicate on the "tag_id" field.
func TagIDIn(vs ...int) predicate.Taggable {
	return predicate.Taggable(sql.FieldIn(FieldTagID, vs...))
}

// TagIDNotIn applies the NotIn predicate on the "tag_id" field.
func TagIDNotIn(vs ...int) predicate.Taggable {
	return predicate.Taggable(sql.FieldNotIn(FieldTagID, vs...))
}

// TagIDGT applies the GT predicate on the "tag_id" field.
func TagIDGT(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldGT(FieldTagID, v))
}

// TagIDGTE applies the GTE predicate on the "tag_id" field.
func TagIDGTE(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldGTE(FieldTagID, v))
}

// TagIDLT applies the LT predicate on the "tag_id" field.
func TagIDLT(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldLT(FieldTagID, v))
}

// TagIDLTE applies the LTE predicate on the "tag_id" field.
func TagIDLTE(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldLTE(FieldTagID, v))
}

// AddedByEQ applies the EQ predicate on the "added_by" field.
func AddedByEQ(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldAddedBy, v))
}

// AddedByNEQ applies the NEQ predicate on the "added_by" field.
func AddedByNEQ(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldNEQ(FieldAddedBy, v))
}

// AddedByIn applies the In predicate on the "added_by" field.
func AddedByIn(vs ...string) predicate.Taggable {
	return predicate.Taggable(sql.FieldIn(FieldAddedBy, vs...))
}

// AddedByNotIn applies the NotIn predicate on the "added_by" field.
func AddedByNotIn(vs ...string) predicate.Taggable {
	return predicate.Taggable(sql.FieldNotIn(FieldAddedBy, vs...))
}

// AddedByGT applies the GT predicate on the "added_by" field.
func AddedByGT(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldGT(FieldAddedBy, v))
}

// AddedByGTE applies the GTE predicate on the "added_by" field.
func AddedByGTE(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldGTE(FieldAddedBy, v))
}

// AddedByLT applies the LT predicate on the "added_by" field.
func AddedByLT(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldLT(FieldAddedBy, v))
}

// AddedByLTE applies the LTE predicate on the "added_by" field.
func AddedByLTE(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldLTE(FieldAddedBy, v))
}

// AddedByContains applies the Contains predicate on the "added_by" field.
func AddedByContains(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldContains(FieldAddedBy, v))
}

// AddedByHasPrefix applies the HasPrefix predicate on the "added_by" field.
func AddedByHasPrefix(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldHasPrefix(FieldAddedBy, v))
}

// AddedByHasSuffix applies the HasSuffix predicate on the "added_by" field.
func AddedByHasSuffix(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldHasSuffix(FieldAddedBy, v))
}

// AddedByIsNil applies the IsNil predicate on the "added_by" field.
func AddedByIsNil() predicate.Taggable {
	return predicate.Taggable(sql.FieldIsNull(FieldAddedBy))
}

// AddedByNotNil applies the NotNil predicate on the "added_by" field.
func AddedByNotNil() predicate.Taggable {
	return predicate.Taggable(sql.FieldNotNull(FieldAddedBy))
}

// AddedByEqualFold applies the EqualFold predicate on the "added_by" field.
func AddedByEqualFold(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldEqualFold(FieldAddedBy, v))
}

// AddedByContainsFold applies the ContainsFold predicate on the "added_by" field.
func AddedByContainsFold(v string) predicate.Taggable {
	return predicate.Taggable(sql.FieldContainsFold(FieldAddedBy, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.Taggable {
	return predicate.Taggable(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.Taggable {
	return predicate.Taggable(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.Taggable {
	return predicate.Taggable(sql.FieldLTE(FieldSortOrder, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Taggable) predicate.Taggable {
	return predicate.Taggable(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Taggable) predicate.Taggable {
	return predicate.Taggable(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Taggable) predicate.Taggable {
	return predicate.Taggable(sql.NotPredicates(p))
}
