// Code generated by ent, DO NOT EDIT.

package folder

import (
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/entx/testentpoly/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Folder {
	return predicate.Folder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Folder {
	return predicate.Folder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Folder {
	return predicate.Folder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Folder {
	return predicate.Folder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Folder {
	return predicate.Folder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Folder {
	return predicate.Folder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Folder {
	return predicate.Folder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Folder {
	return predicate.Folder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Folder {
	return predicate.Folder(sql.FieldLTE(FieldID, id))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v string) predicate.Folder {
	return predicate.Folder(sql.FieldEQ(FieldParentID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Folder {
	return predicate.Folder(sql.FieldEQ(FieldName, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v string) predicate.Folder {
	return predicate.Folder(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v string) predicate.Folder {
	return predicate.Folder(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...string) predicate.Folder {
	return predicate.Folder(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...string) predicate.Folder {
	return predicate.Folder(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v string) predicate.Folder {
	return predicate.Folder(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v string) predicate.Folder {
	return predicate.Folder(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v string) predicate.Folder {
	return predicate.Folder(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v string) predicate.Folder {
	return predicate.Folder(sql.FieldLTE(FieldParentID, v))
}

// ParentIDContains applies the Contains predicate on the "parent_id" field.
func ParentIDContains(v string) predicate.Folder {
	return predicate.Folder(sql.FieldContains(FieldParentID, v))
}

// ParentIDHasPrefix applies the HasPrefix predicate on the "parent_id" field.
func ParentIDHasPrefix(v string) predicate.Folder {
	return predicate.Folder(sql.FieldHasPrefix(FieldParentID, v))
}

// ParentIDHasSuffix applies the HasSuffix predicate on the "parent_id" field.
func ParentIDHasSuffix(v string) predicate.Folder {
	return predicate.Folder(sql.FieldHasSuffix(FieldParentID, v))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.Folder {
	return predicate.Folder(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.Folder {
	return predicate.Folder(sql.FieldNotNull(FieldParentID))
}

// ParentIDEqualFold applies the EqualFold predicate on the "parent_id" field.
func ParentIDEqualFold(v string) predicate.Folder {
	return predicate.Folder(sql.FieldEqualFold(FieldParentID, v))
}

// ParentIDContainsFold applies the ContainsFold predicate on the "parent_id" field.
func ParentIDContainsFold(v string) predicate.Folder {
	return predicate.Folder(sql.FieldContainsFold(FieldParentID, v))
}

// ParentTypeEQ applies the EQ predicate on the "parent_type" field.
func ParentTypeEQ(v ParentType) predicate.Folder {
	return predicate.Folder(sql.FieldEQ(FieldParentType, v))
}

// ParentTypeNEQ applies the NEQ predicate on the "parent_type" field.
func ParentTypeNEQ(v ParentType) predicate.Folder {
	return predicate.Folder(sql.FieldNEQ(FieldParentType, v))
}

// ParentTypeIn applies the In predicate on the "parent_type" field.
func ParentTypeIn(vs ...ParentType) predicate.Folder {
	return predicate.Folder(sql.FieldIn(FieldParentType, vs...))
}

// ParentTypeNotIn applies the NotIn predicate on the "parent_type" field.
func ParentTypeNotIn(vs ...ParentType) predicate.Folder {
	return predicate.Folder(sql.FieldNotIn(FieldParentType, vs...))
}

// ParentTypeIsNil applies the IsNil predicate on the "parent_type" field.
func ParentTypeIsNil() predicate.Folder {
	return predicate.Folder(sql.FieldIsNull(FieldParentType))
}

// ParentTypeNotNil applies the NotNil predicate on the "parent_type" field.
func ParentTypeNotNil() predicate.Folder {
	return predicate.Folder(sql.FieldNotNull(FieldParentType))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Folder {
	return predicate.Folder(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Folder {
	return predicate.Folder(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Folder {
	return predicate.Folder(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Folder {
	return predicate.Folder(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Folder {
	return predicate.Folder(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Folder {
	return predicate.Folder(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Folder {
	return predicate.Folder(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Folder {
	return predicate.Folder(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Folder {
	return predicate.Folder(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Folder {
	return predicate.Folder(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Folder {
	return predicate.Folder(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Folder {
	return predicate.Folder(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Folder {
	return predicate.Folder(sql.FieldContainsFold(FieldName, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Folder) predicate.Folder {
	return predicate.Folder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Folder) predicate.Folder {
	return predicate.Folder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Folder) predicate.Folder {
	return predicate.Folder(sql.NotPredicates(p))
}
